### ISSUE TITLE
make PARANOID_MODE do something in tests

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#1080]
"I would like to mention here that this bug was not catched by our unit tests. ManageDataTests.cpp contains tests for adding, changing and modyfing DATA ledger entries, it even runs with PARANOID_MODE=true. But unfortunately, it never closes the ledger which causes checkAgainstDatabase to be called. So the PARANOID_MODE=true has no effects on these tests at all. I think that either applyCheck() should close a ledger with only one transaction (I've tried that, but there are some issues to be resolved), or at least LedgerDelta::checkAgainstDatabase() should be called manually around app.getLedgerManager().checkDbState(); call (tried that one as well, works good and finds the bug mentioned above). I'll be happy with either change, but closing ledger seems to test behavior matching live node more closely." - rafal

**Comment by MonsieurNicolas** [comment]
I think it would make sense to change `applyCheck` (and friends) to invoke as much as possible of the ledger close common code. I know the trick here is to bypass most of the herder logic that would discard bad transactions.

Maybe something that we should look at doing for the next round of invariant checks so that most test cases will run with all invariants enabled.

 @jonjove  I am assigning this to you so that you keep track of this.

**Comment by MonsieurNicolas** [comment]
the way invariants are coded makes this obsolete
