### ISSUE TITLE
Allow NAT peers

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1086]
When PEER is behind NAT it should present itself with listening port set to 0, as it is not possible to connect to such peer.

This requires allowing setting PEER_PORT = 0.

Such peers do not need to be stored in database or flooded across network. PeerRecord class does not allow port set to 0, so all instantiation of it should be checked and guarded against it.

Also check noteHandshakeSuccessInPeerRecord - when this is implemented, noteHandshakeSuccessInPeerRecord should not drop peer when port == 0.

**Comment by MonsieurNicolas** [comment]
I don't think nodes should be flooding nodes that they can't get to, which should limit how far into the network those guys would propagate. 
What kind of problem is this causing right now? a node behind a NAT should still be able to connect to the rest of the network - or is it that it's eventually marked as a bad peer because nodes can't connect to it?

**Comment by MonsieurNicolas** [comment]
I think that #1807 makes this irrelevant

**Comment by MonsieurNicolas** [comment]
we distinguish inbound from outbound peers now, and don't advertise peers that are unreachable
