### ISSUE TITLE
Better explanation / mention of FAILURE_SAFETY options

### ISSUE THREAD

**Issue by zachvanduyn** [stellar/stellar-core#1288]
I struggled to find a definition on the difference between 1, -1, etc.

**Comment by MonsieurNicolas** [comment]
The current blurb that explains that configuration is there https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_example.cfg#L177-L184 .

**Comment by MonsieurNicolas** [comment]
Was it that the doc was not clear or that you didn't know where to find it?

**Comment by zachvanduyn** [comment]
Basically, if a user goes the Docker route, this example config isn't what is used, missing the explanation.

If I am setting up a validator and drop in that example config, it's missing the nice explanation.

(https://github.com/stellar/docs/blob/master/other/stellar-core-validator-example.cfg)

The only way to get to the `stellar-core_example.cfg` is to look at the Github repo, not the Stellar Developer docks.

**Comment by MonsieurNicolas** [comment]
Oh I see, the dreaded "copy/paste" :)

At a minimum we should point back to the source so that people can easily find the documentation.

I would recommend opening an issue for the `docs` repo to change how this file should be managed. Typicaly validator should not set the `FAILURE_SAFETY` option as the list of nodes from the network should be curated to be a list of reliable nodes.
