### ISSUE TITLE
Failing invariant tests

### ISSUE THREAD

**Issue by PJvGrol** [stellar/stellar-core#1380]
# Issue type
* Bug

# Version found
  * commit be645dff

# Your environment and setup
  * Windows 10 Pro
  * Running from Microsoft Visual Studio 2017 (15.4.3)
  * Debugging using parameters --test [bucketlistconsistent]

# Issue description
* At least the following tests fail: BucketListIsConsistentWithDatabase succeed, multiple applies, added entries, deleted entries, modified entries. All tests fail with the following message:
"FAILED: due to unexpected exception with message:  
sqlite3_statement_backend::loadOne: UNIQUE constraint failed: offers.offerid"  
* Steps taken: debugging seems to point at OfferFrame::exists (https://github.com/stellar/stellar-core/blob/master/src/ledger/OfferFrame.cpp line 300) as the likely culprit. The function checks whether given combination of offerid and sellerid is already in the database, and returns true if it is. The unique constraint on offer, however, is just offerid, which means that, if we have two offer entries with the same offerid and a different sellerid, exists takes it as two unique entries, whereas the table only sees it as one.
* I've tried making (offerid, sellerid) the primary key, as well as restricting OfferFrame::exists to checking just the offerid. Both produced different errors.

## Actual result
 *Tests failed*

## Expected result
 *Tests should have succeeded*

## Supporting files
Looking at the raw log found via https://travis-ci.org/stellar/stellar-core/jobs/301519084 and searching for "Failed" seems to point at a lot of invariant tests failing, despite the TravisCI stating that all tests succeeded.  
Example of such a line in Travis:  
* Database = 29 [InvariantManagerImpl.cpp:83]
2017-11-13T17:55:33.532 <test> [Invariant FATAL] invariant "BucketListIsConsistentWithDatabase" does not hold on bucket Snap[2] = d29d0473b11b51069fdb04a4189bca1a7048f1d589bdb63a4710347ef8133abc: Incorrect Account count: Bucket = 31

# Note for VS users
You likely have to manually add BucketListIsConsistentWithDatabase.cpp, BucketListIsConsistentWithDatabaseTests.cpp and BucketListIsConsistentWithDatabase.h to the .vcxproj files, or the build won't succeed.

**Comment by MonsieurNicolas** [comment]
Thanks for looking into this! This was just merged. I am opening an issue for the vsproject file out of sync (I know, we could use CMake or something instead :-D ).

It looks like there is at least a problem with the test itself: `offerid` is supposed to be unique so it is correct (ie: no need to try to make it).

As for invariant failures in other places, I don't have access to the logs you pointed to so can't confirm, I know that we have a lot of negative tests (basically checking that invariants are being tripped if we mess with the data) - but @jonjove should be able to investigate this further and confirm.

**Comment by PJvGrol** [comment]
The link was the raw log of the TravisCI used by stellar. I've updated the link to not directly reference the raw log, but the page just before it.

**Comment by MonsieurNicolas** [comment]
If the failures are expected - I agree that we should probably change the code not to output all of this garbage :) I know that @jonjove was working on improvements to the way invariants are triggered, he should be able to take care of that at the same time.

**Comment by jonjove** [comment]
Hi @PJvGrol, thank you for reporting this issue. Before I look further into this issue, I wanted to confirm that you compiled this with the expected version of xdrpp (as of commit 1925c20 which was included in #1318, the HEAD of xdrpp should be at a94045de)? For older versions of xdrpp, it is expected that these tests should fail with errors similar to what you shared above. If you compiled with the expected version of xdrpp and are still encountering these issues, please let me know and I am happy to look into the issue more deeply.

With regard to the error messages indicating that invariants did not hold, this is caused by the fact that there are many tests checking that errors are thrown when the data is incorrect, exactly as @MonsieurNicolas indicated above. I agree that they end up causing a lot of noise in the log file (one might wonder why is there an error message when something succeeded?) so I will remove those error messages from the tests in a future PR.

**Comment by PJvGrol** [comment]
Hello @jonjove , thank you for the quick response. I can now confirm that the tests do indeed pass with xdrpp at a94045de. For some reason (well, I must've made a mistake somewhere) my copy of stellar was still using the previous head of xdrpp, even though I ran submodule update. Recloning the repository solved this.
