### ISSUE TITLE
Data layer consolidation

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1417]
Right now we have a few data structures used to keep track of ledger entry state in our code base:
* "backend" calls to soci (SQL), where we perform CRUD and transactions
  * this layer also has a simple cache
* LedgerDelta construct used to build the input to the BucketList, also supports CRUD and transactions

Currently, the code is written in such a way that it's the caller's responsibility to always perform both calls to each subsystem correctly; it's also the caller's responsibility to keep track of objects in memory. 

We should be able to consolidate those calls behind a single data layer API that would perform the proper calls to the various subsystems.

With this we should also be able to:
* simplify the client code that would not have to worry about transactions being rolled back in one system but not the other
* move towards "in memory" transactions (not use nested SQL transactions in the typical case)
* detect (or better, not allow by switching to better semantics) the use of stale data in business logic
   * reads from a cached copy object that was updated later on (ie shadowing effect)
   * writes from an old copy (ie rollback effect)

**Comment by jonjove** [comment]
Before embarking on implementing the changes mentioned in this issue by @MonsieurNicolas, I wanted to share an overview of the rough design that I have created so that it can be critiqued.

The primary design goals for the new data layer are:
1. Consolidate `soci::transaction` and the transaction-like behavior of `LedgerDelta` into a single object, so that the user of `LedgerDelta` does not need to manage both.
2. Eliminate the need for nested SQL transactions.
3. Reduce the possibility of referring to incorrect data in business logic.
4. Achieve goals 1-3 in a manner that minimizes the number of changes required in code that uses the current data layer.

I first introduce the `LedgerState` object, which is an abstraction for a store of Accounts/TrustLines/Offers/Data (referred to as LedgerEntries from this point forward). Specifically, `LedgerState` is a hybrid of in-memory storage and Database storage. `LedgerState` additionally emulates (potentially nested) Database transactions without utilizing nested SQL transactions. It follows that `LedgerState` implements

- `void commit()`
- `void rollback()`

and `rollback` is called by `LedgerState::~LedgerState` if neither `commit` nor `rollback` have been invoked manually. The behavior of `commit` depends on whether the `LedgerState` is nested or not:

- If the `LedgerState` has a child, then `commit` will throw.
- If the `LedgerState` is nested then `commit` merges the changes it has stored in memory into its parent.
- Else, the `LedgerState` opens a SQL transactions and merges the changes it has stored in memory into the Database.

The behavior of `rollback` does not depend on whether the `LedgerState` is nested or not:

- If the `LedgerState` has a child, then it will recursively `rollback` the child before performing the `rollback` on itself. This behavior is required for `LedgerState::~LedgerState` to be able to call `rollback` without throwing exceptions.
- `rollback` discards the changes that the `LedgerState` has stored in memory.

Therefore, goals 1 and 2 are achieved.

Because `LedgerState` is a hybrid of in-memory storage and Database storage, it must provide the only interface to the Database; for otherwise, it would be possible to read directly from the Database when there are in-memory changes. Therefore, `LedgerState` implements

- `std::shared_ptr<LedgerStateReference> create(LedgerEntry)`
- `std::shared_ptr<LedgerStateReference> load(LedgerKey)`

where the `LedgerStateReference` object is an uncopyable, unmovable wrapper around a pointer to a LedgerEntry which can only be constructed by `LedgerState`. In this sense, `LedgerStateReference` satisfies a uniqueness constraint. When `LedgerStateReference` is constructed, it is in the valid state but it can be moved into the invalid state by

- `void invalidate()`

which it implements. When `LedgerStateReference` enters the invalid state, it can never become valid again. Attempting to call any member function of the `LedgerStateReference` when it is in the invalid state will result in a thrown exception. This functionality is useful to make nested transactions less error prone. Whenever a nested `LedgerState` is constructed, the parent will call `invalidate` on every `LedgerStateReference` that it has stored in memory. This makes it extremely difficult to accidentally use stale data in business logic. `LedgerStateReference` also implements

- `LedgerEntry& entry()`
- `void erase()`

which can be used to update the underlying LedgerEntry data. Any updates are automatically reflected in the `LedgerState`. I can now describe the implementation of `create` and `load`. The behavior of `create` is:

- If the `LedgerState` (or a parent) has this key in memory:
    - If it has not been erased, then throw.
- Else if the key exists in the Database, then throw.
- Else, create a new `LedgerStateReference` corresponding to this LedgerEntry.

Similarly, the behavior of `load` is:

- If the `LedgerState` (or a parent) has this key in memory:
    - If it is valid, then throw.
    - Else, create a new `LedgerStateReference` corresponding to the found `LedgerStateReference`.
- Else attempt to load this key from the Database:
    - If it is not found, then throw.
    - Else, create a new `LedgerStateReference` corresponding to the LedgerEntry loaded from the database.

The constraints on `create` and `load` combined with the uniqueness constraint of `LedgerStateReference` implies that there is at most one valid `LedgerStateReference` corresponding to any given key. This achieves goal 3.

In order to minimize the required changes in code utilizing the existing data layer, I will provide a family of wrappers for `LedgerStateReference` that correspond to the existing `*Frame` classes. These wrappers will implement the exact interface of the existing `*Frame` classes except for those functions related to interacting with the Database. This should make them as close to drop-in replacements as possible. This achieves goal 4.

**Comment by vogel** [comment]
Hello.

I like most of the design, but I think there is room for a few improvements.
First: `LedgerState` can only have 0 or 1 child `LedgerState` at a time. If the would be similar to current `LedgerDelta` that accepts parent `LedgerDelta` in its constructor `explicit LedgerDelta(LedgerDelta& outerDelta);` _(note: `LedgerDelta` copy constructor is not making a copy in current design)_. then it could be possible to make 2 `LedgerState` objects be child of the same parent objects. This is probably not what we want (until we implement multithreaded stellar-core, which may be or not be possible).

I propose wrapping `LedgerState` chain in a class that manages those relations and adds/removed LedgerState as a child to current leaf state. It could also implement `create` and `load` methods itself and forward it into leaf state object. Then it will be possible to add RAII type class to add/remove state objects from that wrapper class. It could look like this:

```
void doSomeOperation(Operation &op, LedgerStateChain &chain)
{
  LedgerStateRAII raii{chain}; // this creates new LedgerState and sets it as child to last one in chain
  auto x = chain.load(....); // 
  x.setBalance(10000000000000);
  chain.commit(); // leaf LedgerState will be commited in chain
} // destroys raii object, and commits LedgerState, if exception was thrown it does rollback
```

Second, I don't like the idea of keeping wrapper to `*Frame` objects. We should have only one way of doing one thing, and we control the codebase. So please either drop that point from this design overview or add a line that will say `those wrappers will be replaced by proper `LedgerStateReference` usage in the last commit of the PR.

**Comment by jonjove** [comment]
Hi @vogel,

Thank you for the comments! I think I was unclear in some aspects of the design. 

Specifically, I think I didn’t provide enough implementation information about the nesting of `LedgerState` objects. I completely agree that `LedgerState` should have at most one child (at any given time; it must be possible for a child to be committed or rolled back then a new one created). Unlike `LedgerDelta`, `LedgerState` must know both its parent (in order for `commit` to work correctly) and its child (in order for recursive `rollback` to work correctly). Therefore the design I had in mind was for `LedgerState` to be uncopyable and unmovable, and any attempt to create a new `LedgerState` with a specified parent will throw if the parent already has a child. I believe that this makes it impossible for two `LedgerState` objects to have the same parent.

With regard to the `LedgerStateChain` proposal, I think my above clarifications make it clear that `LedgerStateChain` provides almost the exact interface that `LedgerState` already implements. `LedgerState` is itself an RAII class that handles adding/removing itself from the sequence of nested `LedgerState` objects. Specifically, calling `commit` or `rollback` on a `LedgerState` that has a parent will update the parent to reflect the new status of its children. Since `rollback` is automatically called by `LedgerState::~LedgerState` if neither `commit` nor `rollback` were manually called, `LedgerState` is guaranteed to properly manage the chain. Please correct me if I didn’t fully understand the proposal here.

I think I also was insufficiently clear about the wrappers for `LedgerStateReference` that correspond to the existing `*Frame` classes. For concreteness, let’s consider the existing `AccountFrame` object. It’s interface consists of some functions for accessing and modifying the underlying data (for example, `getBalance` and `addBalance`) as well as some functions for interfacing with the Database such as `storeAdd`, `storeChange`, and `storeDelete`. I propose introducing a corresponding class `AccountReference` and removing `AccountFrame`. The interface of `AccountReference` will consist only of functions for accessing and modifying the underlying data (for example, `getBalance` and `addBalance`) because the Database interface functions no longer make sense. The implementation will now depend on the notion of `LedgerStateReference`. The plan is for `AccountReference` to be constructible from `std::shared_ptr<LedgerStateReference>`. Consider the function `AccountFrame::getBalance`. The corresponding implementation in `AccountReference` could (note: this implementation is only for illustrative purposes) look like
```
int64_t AccountReference::getBalance()
{
    // mEntry is a member of type std::shared_ptr<LedgerStateReference>
    // LedgerStateReference::entry() throws if the state is invalid
    return mEntry->entry().data.account().balance;
}
```
so the properties of the underlying `LedgerStateReference` are preserved in this manner. Then it is possible to do something like
```
LedgerState ls(…);
AccountReference ar = ls.load(…);
ar.setBalance(…);
ls.commit();
```
In some sense, you can think of `LedgerStateReference` as analogous to `LedgerEntry`: it contains data but it does not have any convenience functions associated with it to make using the data easy. Then `AccountReference` can be thought of as a convenient and familiar interface to the underlying data. All of the above applies similarly for the other `*Frame` classes. The purpose of this is that it should be extremely easy to substitute the `*Reference` classes where the `*Frame` classes are already in use. If we did not do something like this, then every usage of `*Frame` would have to be modified substantially which is undesirable. @MonsieurNicolas and I discussed this particular issue and length during an early phase of the design process. Please let me know if you still think that this is a design flaw.

I also want to clarify that, at the end of this process, the `*Frame` objects will be removed. `LedgerDelta` will be removed as well, since it’s functionality has been incorporated into `LedgerState`.

**Comment by vogel** [comment]
I understand now and I like the new `AccountReference`! Great that we will get rid of `*Frame` classes (I was never big fan of those).

And for the `LedgerState`, I split bugs into several categories:
* found by user
* found by compiler
* not possible to make

With your proposal, throwing when creating two `LedgerState` with the same parent falls under "found by user" category. With my version, it is just not possible to make (as creating two raii objects in the same scope will just make two `LedgerState`, first one will make its parent previous leaf `LedgerState` and second one will make its parent the first one).

For example:
```
void applyTx(Tx tx, LedgerState parent)
{
  LedgerState txChild{parent};
  for (auto op : tx.ops)
  {
    LedgerState opChild{parent}; // ovbious mistake, will compile and crash
    applyOp(op);
    opChild.commit();
  }
  txChild.commit();
}
```

vs

```
void applyTx(Tx tx, LedgerStateChain chain)
{
  LedgerStateRAII txRAII{chain};
  for (auto op : tx.ops)
  {
    LedgerStateRAII opRAII{chain}; // will do what is needed
    // not possible to make mistake here
    applyOp(op);
    opRAII.commit();
  }
  txRAII.commit();
}
```

**Comment by MonsieurNicolas** [comment]
Yeah, the chain idea is interesting - but it makes tracking down the parent transaction harder.
I am not worried about the "found by user" behavior here as it's going to crash all the time.
So I am more interested in making it easy to navigate the code, which I think the current proposal biases for, as I can simply search for the parent transaction variable to find the parent transaction (which may be a few scopes above).

**Comment by jonjove** [comment]
Thanks for the explanation @vogel, I understand your proposal much better now! I find this idea very interesting. I agree with @MonsieurNicolas that explicitly giving the parent makes it easier to navigate the code, but using `LedgerStateChain` makes it easy to ensure that you never accidentally open a `LedgerState` without referencing a parent if one exists. Consider the following wrong code that you could write without `LedgerStateChain`:
```
LedgerState ls;
LedgerState ls2; // Did not specify ls as parent here, error!
```
But this would be impossible with `LedgerStateChain`, unless you explicitly constructed your own `LedgerStateChain` which would be a strong indication that you have made an error. 

You could take this further and make it so that only `Application` can construct a `LedgerStateChain`. When `Application` is initialized it could create `std::shared_ptr<LedgerStateChain>` that is to be shared by the entire `Application`. Then when you want to create a `LedgerState` it could look like:
```
auto chain = app->getLedgerStateChain();
LedgerState ls{chain};
LedgerState ls2{chain};
```
This logic error has now become impossible.

I think the benefit of making this logic error impossible may be worth the added difficulty of navigating the code. Let me know what you think.

**Comment by MonsieurNicolas** [comment]
Yeah I think that I would go with the ledger chain if we were not always failing but because we are I don’t think the trade off is worth it

**Comment by vogel** [comment]
Last question is: how will you handle changes to LedgerHeader?
Currently there is that odd solution that each LedgerDelta gets reference and copy of some LedgerHeader structure, but in reality most of the data is changed in LedgerManagerImpl::closeLedger, and some in ManageOfferOpFrame.

**Comment by MonsieurNicolas** [comment]
re-reading the comment from @jonjove 

You are pointing to a different problem with the example:
```
LedgerState ls;
LedgerState ls2; // Did not specify ls as parent here, error!
```
the problem here is that `LedgerState` should not have a default constructor like this.

I imagine that the "top level" `LedgerState` should be created using some special factory that takes a bunch of parameters so that it can bind to the database, cache and `LedgerManager` state (and that top level guy is only accessible through a special method).
so really this example would look like:
```
LedgerState ls(app.StateManager().State());
LedgerState ls2(app.StateManager().State()); // compiles, but looks fishy
```
which will crash as ls2 will attempt to create a second child to the top level `StateManager` as soon as ls2 is created.

In the ledger chain world, the code "will look just fine" and issues like this one will just be crashing at a later stage:
```
auto chain = app->getLedgerStateChain();
LedgerState ls{chain};
LedgerState ls2{chain};
// ...
// code is buggy - likely to use ls instead of ls2
AccountReference ar = ls.load(…); /// crash (pending child transaction)
ar.setBalance(…);
```

**Comment by vogel** [comment]
What about:
```
auto chain = app->getLedgerStateChain();
LedgerState ls{chain};
LedgerState ls2{chain};
// ...
// code is buggy - likely to use ls instead of ls2
// AccountReference ar = ls.load(…); /// not possible, no such public API
AccountReference ar = chain.load(…);  /// uses private API or last LedgerState on chain by being friend
ar.setBalance(…);
```

**Comment by MonsieurNicolas** [comment]
We've decided to work on this now but not ship it in 10.0.0
