### ISSUE TITLE
stellar-core needs better log handling

### ISSUE THREAD

**Issue by smdwireless** [stellar/stellar-core#1428]
Stellar-core creates an enormous log file over time unless you completely disable (dump) the logs.

This can create problems if you want to maintain High-availability with stellar-core. As the server does not currently support `reload` if we use log-rotate, the service is restarted at the time of log rotation. This causes service disruption while the restarted instance re-synchs to reach consensus.

My suggestion is that either stellar-core needs:

1) A way to allow configuration of a log-file limit and naming scheme for each new file that is created when that limit is reached, which can be managed from stellar-core.cfg

or

2) to introduce support for `reload` so that it can work with log-rotate without disruption.

A reloaded instance would allow it to continue the running of the service from memory while disk-write processes such as log-file writes are disrupted temporarily such as is the case with common servers such as mysql or apache web server.

**Comment by MonsieurNicolas** [comment]
Thanks for the report.

We currently support two ways to do log rotate:
* use the built-in log rotation
  * By default stellar-core outputs to a file with the pattern `stellar-core.%datetime{%Y.%M.%d-%H:%m:%s}.log` 
  * combine this with the `logrotate` command and a new log file will be created
     * the documentation is wrong on the default (it says that it's `stellar-core.log` which would cause `logrotate` to not do anything as the filename ends up being constant)
* make `stellar-core` output to stdout instead of a log file (this is how we do log rotation at SDF)
   * this is done by setting `LOG_FILE_PATH` to an empty string.
   * log rotation is then implemented by whatever launcher/daemon was used to start the `stellar-core` process

I realize that both of these are poorly documented - I am going to use this issue to track improvement to the `admin.md` docs.

**Comment by MonsieurNicolas** [comment]
I also prototyped a simple change that would make log rotation work on linux systems (right now it seems we cannot use the logrotate semantics of move + close + reopen that log-rotate depends on to not lose data).

**Comment by MonsieurNicolas** [comment]
punting - easylogging changes in upstream still pending review

**Comment by MonsieurNicolas** [comment]
punting again - still waiting on https://github.com/muflihun/easyloggingpp/pull/593

**Comment by marta-lokhova** [comment]
resolved by #1824
