### ISSUE TITLE
txBAD_AUTH_EXTRA Signature bug

### ISSUE THREAD

**Issue by johansten** [stellar/stellar-core#1464]
I was trying out something I'd thought would be a simple thing yesterday, and I still can't figure it out.

I have two accounts, `ownerId` and `assetId`. When this starts, `assetId` has masterweight = 0, and is signed for by `ownerId`.

My transaction tries to change back master weight to 1, remove `ownerId` as a signer, before finally merging `assetId` back into `ownerId`. It fails.

```
return horizon.loadAccount(ownerId)
.then(function (account) {
    return new stellar.TransactionBuilder(account)
    .addOperation(stellar.Operation.setOptions({
        source: assetId,
        masterWeight: 1,
        signer: {
            ed25519PublicKey: ownerId,
            weight: 0
        }
    }))
    .addOperation(stellar.Operation.accountMerge({
        source: assetId,
        destination: ownerId
    }))
    .build();
});
```

`ownerId` is the envelope source account, and pays for the fees.
`assetId` is the source account for all the individual operations.

Before setOptions, `assetId` is signed for by `sourceId`
Before accountMerge, `assetId` is signed for by itself.

By now it should be clear that both accounts need to sign the transaction.
So why does this result in a failure of not all signatures being used? None of the signatures on their own are enough.

https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAIMQY6sfxBUJuz9KxDd7XTlymmYQ1Yvl41noMjNWqVrEAAAAyABbLc8AAAACAAAAAAAAAAAAAAACAAAAAQAAAABSZn6pw9muRSb60r3%2BVmVDYvEVAqy8TtUpdT6BZbpKFgAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAIMQY6sfxBUJuz9KxDd7XTlymmYQ1Yvl41noMjNWqVrEAAAAAAAAAAEAAAAAUmZ%2BqcPZrkUm%2BtK9%2FlZlQ2LxFQKsvE7VKXU%2BgWW6ShYAAAAIAAAAAIMQY6sfxBUJuz9KxDd7XTlymmYQ1Yvl41noMjNWqVrEAAAAAAAAAAJWqVrEAAAAQMpPaByRlskf5W%2BDSYgnpsf%2FKdgD1sq%2FTB6szPJOAnqRLEAPj45pMPiPYTb5uPlpMVBnsff7sJFgyZJqIhYnJAllukoWAAAAQI%2B4TDrs5jjGYdmXtiqiEz16Sl44%2Fnr4LP3HzmvLtP%2BXvj5gor%2BlQ7TDV8YUwvzseqDO9PggyQPGs0ufoG2lAwQ%3D&type=TransactionEnvelope&network=test

**Comment by MonsieurNicolas** [comment]
yeah that's an expected result with the current validation model:
* at submission time, we do not actually apply the operations, only check signatures, so we don't see the side effects of `setOptions`. So in your example, only `ownerId` is allowed to sign transactions for this account.
* at apply time, you are right that we would need both signatures to perform the sequence in this particular transaction

so... this particular sequence is not possible with the current design.

The reason we have to make it work like this is that:
* we cannot allow for extra signatures of transactions in order to avoid malleability attacks - so we're stuck with requiring only one signature in the first phase until we can perform full validation of transactions upstream (not something tractable for a while)
* we could consider the transaction signed later on (only check for signatures before applying transactions) - but then we are potentially allowing unexpected broken sequences between transactions (like tx1 changes its signers does a bunch of prep and expects certain things to be true at the end of the transaction, but tx2 invalidates some of those expectations)

net is: the current behavior is not ideal but is fully deterministic and guarantees isolation between transactions.

**Comment by johansten** [comment]
So submission is:
* collect source accounts and their thresholds
* collect source account signers and accumulate weights

I guess as long as this is spelled out it's fine, but right now I just see a lot of unfulfilled potential, since there are strings of operations that can't possible ever get past the submission stage as-is
if you want to performs things atomically.

:(

**Comment by johansten** [comment]
How about doing a more thorough check after submission finds too many signatures?
It's only setOptions ops that can change the set of signers, it ought to be quick.

**Comment by MonsieurNicolas** [comment]
The problem is that this won't be enough: other transactions may change the signers, so we'd have to somehow figure out how to reorder transactions applied during  ledger (and this is a non starter with the current model).

I think it would potentially make more sense to just say that we do signature verification upfront (ie: verify signatures before applying the transactions) - problem there is that it may make certain assumptions difficult. I think we need to discuss this more in the context of smart contracts.

The closest place we have to discuss this is https://github.com/stellar/stellar-protocol/issues/51

**Comment by johansten** [comment]
Well, to be frank, transactions outside of my tx envelop modifying things just shouldn't matter to me. So what if something passes submission, and then fails? Isn't that better than not being able to run certain transaction *AT ALL*?

**Comment by johansten** [comment]
The more I think about this, the more upset I get.

The only accounts who can modify the signers outside of a transaction are same the accounts who already signed for the source accounts in the transaction.

Why would they knowingly submit two transactions where one will void the other? I don't get it.

**Comment by MonsieurNicolas** [comment]
You should not get upset, it's software not hardware :)
I'm pretty sure we can find a solution that will make this work the way we want.

I also think that by looking at the type of stuff that we want to do with smart contracts it should inform us on the nature of the solution.
In that context: we can have two different transactions competing for an outcome of some sort by modifying signers (ie, one tx wants to enable a set of transactions, another wants to enable a different set) - so yes, while they may have been crafted by the same person, the entities submitting them might be different (and with competing interests) and we have to ensure that there is no way to create unwanted side effects between transactions. What I mean by that is that we want the txs to behave the same way than if they were processed in different ledgers - basically the logic should be fully deterministic and equivalent to "picking" an order for the transactions.

Right now the logic is paranoid and guarantees that property and we verify signatures twice (both before applying and during), which comes with the problems we already discussed.

There has to be a way to relax this while preserving the right properties - this escapes me for now, so any help would be appreciated :)

**Comment by MonsieurNicolas** [comment]
After making the sequence number changes (for `BumpSeqOp`), I think I found a way to fix this that seems satisfactory:
* when a transaction is submitted, do the signature verification the same way than right now
* when a transaction is applied, do the signature verification and perform its side effects (remove the tx hash) *before* applying the operations, this is consistent with how we process sequence numbers in protocol 10 (see the [bumpseq proposal](https://github.com/stellar/stellar-protocol/issues/53) or the [pull request with the actual changes](https://github.com/stellar/stellar-core/pull/1519))

Implications of this:
* when using a pre-image transaction (`SIGNER_KEY_TYPE_PRE_AUTH_TX`) the signer will always be removed (currently, it only gets removed automatically if the transaction succeeds). I don't think it really matters (removing a signer that is already removed is a no-op)
* changing weights may break other transactions like before, but will not effect operations in the same transaction. So it will now be possible to do things like `{ setOptions(masterWeight=0), payment(X->Y) }` (today payment would fail with `BAD_AUTH` as the payment cannot be performed without a valid signature at the time of the operation)
* because we perform signature & weight verification upfront, the behavior wrt `EXTRA_AUTH` is consistent with the check performed when submitting a transaction

Reason I think this works the way we want is that when designing smart contracts the assumptions are still met right at the beginning of any given tx, so even if signers are modified in one transaction, the second transaction will fail as expected.

**Comment by vogel** [comment]
I think I like this solution, it will be more consistent and save us some CPU work:

* if pre-image transaction goes to this stage, it can safely be removed from signers list, as its seqnum was just used, so it cant be used again (I wonder if we need to upgrade our results meta data to show that signer was removed even for failed transaction?)
* allowing stuff like `{ setOptions(masterWeight=0), payment(X->Y) }` won't change much, as it was always possible to do it in opposite direction: `{ payment(X->Y), setOptions(masterWeight=0), }`, with the same effect
* it won't allow behavior asked in `https://github.com/stellar/stellar-protocol/issues/51` (removing signers to disallow creating parties from sending pre-authorized transactions), as it was explained in comments there, the same behavior can be achieved with different techniques (and it creates an interesting discussion topic: do we need/should we add notion of account states/variables and transaction conditions basen on them to better represent what is being done with such an escrow account?)

**Comment by vogel** [comment]
Comments to https://github.com/stellar/stellar-protocol/blob/master/core/cap-0002.md:

1. tx1 currently passes, this is why:

In first pass transaction level verification is done, it requires low threshold that has value 2 at the start of the transaction. This value is obtained by using both signatures - A gives 1, B gives 1. It also marks all signatures as used.

In second pass, operations are verified and signatures are checked per-operation, but this does not matter, as all 2 were already used.

2. tx currently does not pass

In first pass transaction level verification is done, it requires low threshold that has value 2 at the start of the transaction. This value is obtained by using both signatures - A gives 1, B gives 1. It also marks all signatures as used.

Second pass is different from option 1. First operation removes signer B, making it impossible to sign anything more, as all thresholds are bigger than one. So second operation is verified and it does not pass verification. So opBAD_AUTH is returned.

3. not currently possible

There is only one type of one-time-use signatures - hash(tx). Preimage one hash(x) is not implemented as one-time (it must be removed manually by setOptions operation).

So to implement behavior of tx3 we would have to use hash(tx) which would require tx to use hash(tx) as one of its field (in setOptions signer exactly). So it would mean that hash(tx) is part of transaction that after hashing should be hash(tx):

hash(tx) = AAAAA.......hash(tx).......XASEDQ=

That seems like a think that is hard to compute.

4. That may mean that we should make hasj(x) also an one-time signature, that would be easy to use in scenerio like tx3.

**Comment by MonsieurNicolas** [comment]
Unless anybody has objections, we're going to mark the CAP as final and merge the changes (ETA: Monday June 18)
