### ISSUE TITLE
One bucket merge could be executed multiple times

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1482]
We do not cache results of bucket merges. It can cause to suboptimal usage of resources. Imagine not-yet merged `FutureBucket` that goes into `publishqueue` table. If it is at high enough level, it will be created multiple times as result of merge of the same two buckets with the same shadow set - it will lead to the same output bucket each time, which obviously could be cached.

We should add that cache to reduce IO and CPU usage.

**Comment by MonsieurNicolas** [comment]
Why do we resolve pending merges in the publish queue in the first place?

**Comment by vogel** [comment]
Let me look it up in commit history.

**Comment by vogel** [comment]
100% lack of information there - only one commit adding whole HistoryWork stuff.

I think that the only reason this is done it to reduce time it requires nodes to catch up. Comment on `BucketList.h` mentions that, for example, for level 7 merge could take up to 45 minutes. For level 8 it would be 180 minutes, for level 9 720 minutes and for level 10 2880 minutes (2 days).

Doing that merge during catchup is suboptimal.

But also doing that merge during publish means that we do not publish for a long time.

I see 2 part solution here:
1. do not wait with publish until resolving pending merges, instead add a method to update history files when merge is done (this is 100% safe, as FutureBucket is not part of hash)
2. when doing catchup and encountering big bucket merge, go back a few checkpoints and try again to get previous level-10 or level-9 bucket, it would probably take less time to apply more transactions than to wait for a big bucket merge

**Comment by MonsieurNicolas** [comment]
right, from what you are saying it seems that it's basically safer for the network to always publish (without waiting for the merge to be done), so that other nodes can catchup to the network.
Right now if we have a slow merge it potentially opens the possibility of having arbitrary long gaps between checkpoints, which doesn't sound like a good property.

During that time the bucket will show up with inputs but that seems fine. The optimization to fixup the pending merges with the completed merge seems like something we could do later on.

**Comment by MonsieurNicolas** [comment]
@marta-lokhova is working on this
