### ISSUE TITLE
stellar-core cannot be stopped while running tests

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1657]
It looks like the code to properly handle shutdown is done at the application level (`ApplicationImpl::mStopSignals`) but when running tests, there is no "outer application" to handle `SIGINT` and `SIGSTOP`.

Solution is probably to just add a handler in `test` before invoking catch.

There are some subtleties there though:
the naive implementation may not be able to cleanly shutdown the process as tests will continue to run.
even if things shutdown,it's unclear if there is a simple way to cause tests to stop running (equivalent to a critical error)

note: the way catch handles signals seems to be to intercept all signals and trigger the previous handler... but the previous handler is saved at the beginning of the test run, this means that we may have to setup a dummy asio signal handler before invoking catch in order to cause have the asio signal handler installed (see `./asio/detail/impl/signal_set_service.ipp`).

**Comment by MonsieurNicolas** [comment]
I think this is a duplicate of #1954

**Comment by oodlesblockchain** [comment]
Common options can be placed at any place in the command line.

–conf : Specify a config file to use. You can use ‘-’ and provide the config file via STDIN. default ‘stellar-core.cfg’
–ll : Set the log level. It is redundant with http-command ll but we need this form if you want to change the log level during test runs.
–metric : Report metric METRIC on exit. Used for gathering a metric cumulatively during a test run.
–help: Show help message for given command.

Command options can only by placed after command.

catchup <DESTINATION-LEDGER/LEDGER-COUNT>: Perform catchup from history archives without connecting to network. For new instances (with empty history tables - only ledger 1 present in the database) it will respect LEDGER-COUNT configuration and it will perform bucket application on such a checkpoint that at least LEDGER-COUNT entries are present in history table afterwards. For instances that already have some history entries, all ledgers since last closed ledger will be replayed.
check-quorum: Check quorum intersection from history to ensure there is closure over all the validators in the network.
https://bit.ly/35gmqUf
convert-id : Will output the passed ID in all known forms and then exit. Useful for determining the public key that corresponds to a given private key. For example:
$ stellar-core convert-id SDQVDISRYN2JXBS7ICL7QJAEKB3HWBJFP2QECXG7GZICAHBK4UNJCWK2
