### ISSUE TITLE
Manage offer ops rejected with op_low_reserve even when they shouldn't be

### ISSUE THREAD

**Issue by istrau2** [stellar/stellar-core#1708]
# Issue type
  bug

# Version found
  latest protocol

# Issue description
 Trades are rejected with a low_reserve failure even when they should go through. In other words, if I am trying to trade away all my XLM (right down to my reserve), it seems like the protocol assumes like there will be an offer created and so requires 0.5 XLM extra in the reserve (and fails the transaction) even when no offer would be created (because the offer would completely cross another one).

## Actual result
Transaction failed.

## Expected result
I should be able to trade away all of my non-reserved XLM

## Supporting files
Easy to reproduce on pubnet.

**Comment by MonsieurNicolas** [comment]
this is by design: we have to assume that the offer would be created, the alternative would require running managerOffer twice through the order book, first time would be with the assumption that the offer would not be created, and second time with the higher reserve in order to create the offer. To sell XLMs without creating an offer, use path payment.
