### ISSUE TITLE
modify catchup flow to not create "maintenance" debt 

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1747]
Right now the catchup flow goes like this:
1. node starts at ledger N0
2. watch the network, observe ledger N
3. download and apply transactions up to N
4. mark node as "synced"
5. publish backlog

When this is happening, other systems (like Horizon), starts to ingest historical data in parallel.

Current flow causes the `txhistory` (and related) tables to grow to a very large size as cursors (and publish in particular) may not keep up with the amount of data produced.

As the backlog is very large, running `maintenance` becomes a very expensive operation (see #1725 for more information).

## Proposal (to discuss)
We should aim to not get into this situation in the first place.
A solution is to both:
1. run "publish" while catchup is running (this should be possible after the latest changes on the catchup front as we are garanteed that the data is valid)
2. "cap" the amount of data that can be stored in `txhistory` (for example, 2 days worth of ledgers = 17,000 ledgers).
   * When the cap is reached (cursors or publish not keeping up), the node would simply stop closing ledgers
   * note 1: I can see having a setting that would only do this when catching up, not during "normal" operation
   * note 2: a "good" setup would not have to worry about critical validators being stopped because they don't have cursors

**Comment by marta-lokhova** [comment]
From some preliminary investigation, it looks like:
1. We already do publish when catching up 
* When applying a single ledger, `LedgerManager::closeLedger` invokes `HistoryManager::publishQueuedHistory`, so I think we are okay on that front. (and I don't think there's any dependency on #1711, as data is verified in the end of `VerifyLedgerChain` in the current code)

2. The cap number seems pretty big to me. `txhistory` stores each transaction separately, so two days of ledgers would be ~34,000 ledgers * 50 tx = ~1.7M rows, which seems a lot (note this is for worst case scenario. Also, the cap of 50 txs per ledger could also be changed in the future). `ledgerheaders` table doesn't have this problem, as it stores one row per ledger. 
 
3. I think implementation-wise, we would need the following:
* a setting in CatchupWork, which can be determined based on cursor state (if any) and the size of catchup. Do you think it makes sense to have a config to opt out of "waiting for cursor"? (as in, maybe the user is ok doing a one-off maintenance with full vacuum instead of trying to throttle catchup)

* An efficient way of checking if the cap is reached (simply every 34,000 ledgers? Or there might be some kind of heuristic to reduce the number of database roundtrips -- for example, if the cursors are keeping up pretty well, reduce the frequency of checking and otherwise if cursor gets far behind quickly)

* Once the cap is reached, a proper way for catchup work to "wait" -- this makes me think that the new work interface makes a lot of sense as it could utilize WAITING state. Again, I think we'd need some sort of heuristic to understand delay time.
 
4. Also, can you elaborate on this? 
```
note 2: a "good" setup would not have to worry about critical validators being stopped because they don't have cursors
```
I see Horizon uses cursors.

**Comment by marta-lokhova** [comment]
This has a dependency on the new Work interface (#1819), moving to 11.1.0

**Comment by MonsieurNicolas** [comment]
forgot to mention that in order to be able to make more progress again, we have to run "maintenance" as part of the flow (as to avoid building debt) - most likely ignoring the setting for maintenance in that situation

**Comment by marta-lokhova** [comment]
I'm not sure how invested we should be in this, given the upcoming changes in the horizon ingestion flow.

**Comment by MonsieurNicolas** [comment]
yes, let's hold on this for now

**Comment by marta-lokhova** [comment]
ping on this one @MonsieurNicolas: we now have an easy way to throttle catchup via ConditionalWork. I think it's just a matter of whether we're going to implement this (and if so, in which release)

**Comment by MonsieurNicolas** [comment]
yeah we still need to wait on this as the new ingestion in still in flux @marta-lokhova

**Comment by marta-lokhova** [comment]
closing this: the ingestion model has changed in favor of captive core, so we do not need this change anymore
