### ISSUE TITLE
Minor math bug in TransactionUtils.cpp stellar::getMaxAmountReceive

### ISSUE THREAD

**Issue by alex-xage** [stellar/stellar-core#1842]
# Issue type
Bug

# Version found
02b4e88572a8d4c2c1015404e4eb38700cf6c4d6 (current master branch)

# Your environment and setup
N/A, source code inspection

# Issue description
Function stellar::getMaxAmountReceive is defined in src/transactions/TransactionUtils.cpp: https://github.com/stellar/stellar-core/blob/02b4e88572a8d4c2c1015404e4eb38700cf6c4d6/src/transactions/TransactionUtils.cpp#L459-L489

If the data type is `ACCOUNT` then on line 463 `max_receive` is declared as: https://github.com/stellar/stellar-core/blob/02b4e88572a8d4c2c1015404e4eb38700cf6c4d6/src/transactions/TransactionUtils.cpp#L463

On line 464 there is a check for the current ledger version: https://github.com/stellar/stellar-core/blob/02b4e88572a8d4c2c1015404e4eb38700cf6c4d6/src/transactions/TransactionUtils.cpp#L464

If this check returns false then `max_receive` is equal to `INT64_MAX` and is returned on line: https://github.com/stellar/stellar-core/blob/02b4e88572a8d4c2c1015404e4eb38700cf6c4d6/src/transactions/TransactionUtils.cpp#L469

I believe this math is incorrect because in this case `max_receive` should be equal to `INT64_MAX - acc.balance` to avoid an integer overflow. Instead the code in this if statement should mirror the code handling the `TRUSTLINE` data type below: https://github.com/stellar/stellar-core/blob/02b4e88572a8d4c2c1015404e4eb38700cf6c4d6/src/transactions/TransactionUtils.cpp#L476-L481

Thus the correct code would be:
```c++
    if (le.data.type() == ACCOUNT)
    {
        auto const& acc = le.data.account();
        int64_t maxReceive = INT64_MAX - acc.balance;
        if (header.current().ledgerVersion >= 10)
        {
            maxReceive -= getBuyingLiabilities(header, le);
        }
        return maxReceive;
    }
```

## Actual result
On line 463 `max_receive` is declared as `INT64_MAX` and then returned on line 469

## Expected result
On line 463 `max_receive` should be declared as `INT64_MAX - acc.balance` , line 467 should only subtract the amount returned by `getBuyingLiabilities(header, le)` and then `max_receive` should be returned on line 469

## Supporting files
Current code: https://github.com/stellar/stellar-core/blob/02b4e88572a8d4c2c1015404e4eb38700cf6c4d6/src/transactions/TransactionUtils.cpp#L461-L470

Correct code:
```c++
    if (le.data.type() == ACCOUNT)
    {
        auto const& acc = le.data.account();
        int64_t maxReceive = INT64_MAX - acc.balance;
        if (header.current().ledgerVersion >= 10)
        {
            maxReceive -= getBuyingLiabilities(header, le);
        }
        return maxReceive;
    }
```

**Comment by jonjove** [comment]
Hi @alex-xage, thank you for opening this issue. You are correct that this code presents an overflow risk for transactions applied prior to protocol version 10. However this overflow risk actually existed prior to version 10, and was corrected in version 10. The code here is actually a faithful reproduction of the incorrect behavior that existed in the protocol prior to version 10. I do not believe that we should correct this, since such a correction would have been a protocol change (and indeed it was a protocol change as it was fixed in protocol version 10). I have included some analysis of the pathways that can reach this particular branch to indicate that this does reproduce the old behavior.

During transaction application, `getMaxAmountReceive` is only used with a `LedgerEntry` of type `ACCOUNT` in the following circumstances:
- transactions/InflationOpFrame.cpp:90 (if `ledgerVersion` >= 10)
- transactions/ManageOfferOpFrame.cpp:176 (if `ledgerVersion` >= 10)
- transactions/OfferExchange.cpp:86 (in `canBuyAtMost` non-const version)
- transactions/OfferExchange.cpp:103 (in `canBuyAtMost` const version)

`canBuyAtMost` is only used in the following circumstances:
- transactions/ManageOfferOpFrame.cpp:171
- transactions/ManageOfferOpFrame.cpp:421 (if `ledgerVersion` >= 10)
- transactions/OfferExchange.cpp:612 (in `adjustOffer`)
- transactions/OfferExchange.cpp:959 (in `crossOfferV10` which implies `ledgerVersion` >= 10)

`adjustOffer` is only used in the following circumstances:
- herder/Upgrades.cpp:525 (in `updateOffer`)
- herder/Upgrades.cpp:540 (in `updateOffer`)
- transactions/ManageOfferOpFrame.cpp:423 (if `ledgerVersion` >= 10)
- transactions/OfferExchange.cpp:952 (in `crossOfferV10` which implies `ledgerVersion` >= 10)
- transactions/OfferExchange.cpp:1008 (in `crossOfferV10` which implies `ledgerVersion` >= 10)

`updateOffer` is only used in the following circumstances:
- herder/Upgrades.cpp:584 (in `prepareLiabilities`)

`prepareLiabilities` is only used in the following circumstances:
- herder/Upgrades.cpp:728 (in `applyVersionUpgrade` if `ledgerVersion >= 10`)
- herder/Upgrades.cpp:749 (in `applyReserveUpgrade` if `ledgerVersion >= 10`)

The case mentioned in your issue can only occur if `ledgerVersion < 10`. Therefore, of the above pathways there is only one that needs to be inspected: transactions/ManageOfferOpFrame.cpp:171. In release v9.1.0, the corresponding code is transactions/ManageOfferOpFrame.cpp:232,249. Here, we see that `maxWheatCanBuy` (which is analogous to `maxWheatReceive`) is equal to `INT64_MAX` if `wheat.type() == ASSET_TYPE_NATIVE` (this applies for `ledgerVersion < 10` since this code is in the v9.1.0 release). Looking back to 02b4e88, we see that `maxWheatReceive = std::max({getMaxAmountReceive(header, sourceAccount)})` if `wheat.type() == ASSET_TYPE_NATIVE`. Evaluating that call to `getMaxAmountReceive`, we see that `maxWheatReceive = std::max(INT64_MAX, 0) = INT64_MAX` if `ledgerVersion < 10`.

Please let me know if you see something wrong with my analysis, or if you have any other questions on this issue.
