### ISSUE TITLE
Message Size not multiple of 4 error 

### ISSUE THREAD

**Issue by Vishwas1** [stellar/stellar-core#1852]
- I am using stellar-core version `v10.0.0-31-g2c8f3e18-dirty` 
- I am trying to call the core using via http
- This is transaction of type `createAccount`
- Here is the the url
```
http://localhost:11626/tx?blob=AAAAACgsLHXPUv6q9wV8jlzA4cz7ImGwe+cSmF7MlAwP4pzKAAAAZAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAQAAAAAoLCx1z1L+qvcFfI5cwOHM+yJhsHvnEphezJQMD+KcygAAAAAAAAAAhwi8Ls3JfFw2Py5N4jN4jEVTT7dzVgg15neSiNIn4w0AAAAEqBfIAAAAAAAAAAABD+KcygAAAEB+51wzftfQtlOMdyD8ePSfQWaQuQ/sh3tx3Y++TCgGPs/qzd0uq69uY+Mk7ALuMBGEZM9drHym4lkqWRXlnmAI
```
- I parsed the XDR and everything looks good.
- But the core is returning me error - `message size not multiple of 4`
- I am using custom network.

Has anyone encountered this?

**Comment by MonsieurNicolas** [comment]
Hello, please fill in the template with repro steps if this is a bug report and reopen the issue; otherwise ask your question on the other channels.

# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
