### ISSUE TITLE
cursors not respected upon restart

### ISSUE THREAD

**Issue by gracenoah** [stellar/stellar-core#1913]
# Issue type
  bug

# Version found
  v10.0.0

# Your environment and setup
  * Operating System name and version (usually `uname -a`)
    kernel 4.14.65, kubernetes
  * Are you running from the command line? From a container?
     docker container
  * Did you pass in special parameters when building the app?
     no

# Issue description
I have the following configs:

```
CATCUP_RECENT=1440
KNOWN_CURSORS=["HORIZON","CUSTOM"]
```

We manage our own custom cursor in addition to horizon's because we want to scan for deposits ourselves and make sure that history is preserved until we are done with it.

I expected  the behaviour to be: History is retained up to: `min(current ledger sequence - CATCHUP_RECENT, HORIZON, CUSTOM)`

What happened: After down time of 2 hours (enough for just over 1440 ledgers), upon restarting, stellar core spent 3 hours to jump forward and catch up, leaving a gap of 100-200 ledgers.

This looks like a bug. If I set a known cursor, history after it shouldn't have any gaps. What's the point of cursors if down time longer than CATCHUP_RECENT causes gaps? Any I missing something?

**Comment by MonsieurNicolas** [comment]
yeah `CATCHUP_RECENT=1440` means that stellar-core will jump and create gaps if you have more than 2 hours down time. So the answer is: don't use values that small but instead something safe like 3 or 4 days (if you have people on call, otherwise pick even longer).

This is independent from what cursors do: cursors are just a way to tell stellar-core to not delete data that was not ingested by (in this case) Horizon.

Horizon doesn't deal with gaps well (but other systems do), I would recommend reviewing https://www.stellar.org/developers/software/known-issues.html#mismatch-policy-between-stellar-core-and-horizon
and https://www.stellar.org/developers/software/known-issues.html#bridging-the-gap that talks about baking some safety factor into the value for `CATCHUP_RECENT`

**Comment by gracenoah** [comment]
I've read all of the documentation on the topic, but I didn't realize that cursors affect only the gc.

If this is the intended behaviour, I'd like to propose a different behaviour.

I would prefer it if after restart, if there are known cursors and they haven't been updated, stellar core doesn't produce gaps in its catch up behaviour. If other systems are okay with gaps and some would prefer to produce gaps, maybe this can be configurable.

I suspect that it wouldn't be too hard to make this option available and it would prevent gaps from forming accidentally when using stellar core with horizon.

**Comment by MonsieurNicolas** [comment]
We're looking at changing how ingestion works in general, and that seems to be aligned with where we want to go.

There are probably some tricky edge cases with this behavior that will have to be figured out: when cursors are registered, they set their value to "0" (as Horizon is not even started yet), but we may not want to replay full history in this situation (it all depends on which ledger Horizon wants to ingest on startup).

A simple way might be to assume that we can "jump" the very first time (last closed ledger is genesis), but can't perform subsequent jumps after that.

**Comment by gracenoah** [comment]
The proposed behaviour makes sense to me. I assume that the interaction with core's CATCHUP_RECENT would be to just use the earlier of the two?

**Comment by MonsieurNicolas** [comment]
What do you mean by "use the earlier of the two" ?
A consumer (like Horizon) would use its cursor the same way.

**Comment by gracenoah** [comment]
I meant if the cursors are ahead of CATCHUP_RECENT, will CATCHUP_RECENT be used to specify how much history to keep? Sorry, I guess I'm still confused about the interaction between the two.

**Comment by MonsieurNicolas** [comment]
oh I see, the garbage collection process will not change (it's not related to gaps): we only delete data that is safe to delete, so older than the oldest of all cursors

**Comment by vogel** [comment]
After talking with @MonsieurNicolas I think we can propose different solution:
Do not allow for gaps at all.

This means that CATCHUP_MINIMAL, CATCHUP_COMPLETE and CATCHUP_RECENT configuration values only affect the stellar-core if last stored ledger is genesis (or there is no stored ledger at all). For all other cases, CATCHUP_COMPLETE behavior is used.

Rationale: there is no use case that require gaps. Nodes either want full histories (full validators), partial histories from given point of time (anchor validators), or only a current state. We can assume that if node currently allows for gaps in its history, it does not care about history at all. In that case it can just issue new-db after long outage to not do CATCHUP_COMPLETE.

Also code for diffing buckets could be removed in such case, as only full list of buckets could be applied (at the first run), then only transactions are applied. This would simplify code and tests a little bit, which is a good thing. As with recent @graydon changes catchup from buckets is now very fast, we can apply all 22 buckets without waiting for a few hours.

**Comment by graydon** [comment]
Tentatively support this line of reasoning, with one qualifier and one question:

  1. Qualifier: I think you'd want to keep the bucket-diffing code, because it's useful for a node that is _not_ keeping history but that _does_ fall offline for a little while. When it comes back, it can do a fast delta-based catchup without applying all buckets. Applying all buckets is faster now than it used to be, but it's still on the order of many minutes.

  2. Question to confirm I understand what's being proposed: a node that _is_ keeping history, and that falls offline for a few hours or days will still only replay ("completely" -- with no gaps) the window of time between when it fell off and when it rejoins, right? It will not always have to replay from the beginning of time?

**Comment by vogel** [comment]
1. We can keep that, but that will keep all complex code, with all of the current catchup modes, CatchupRange and CatchuoConfiguration variants - that mean no benefit on code complexity. I think we will keep it now as it can be removed independently of rest of the issue.
2. Yes, it will not always start from beginning of time, only from last known ledger.

**Comment by vogel** [comment]
Re 1. again. Reading that again I got to different conclusion. Leaving code for nodes that do not keep history and can accept gap will reduce this PR to 'always do catchup_complete' when cursors are present. No (probably unnecessary) complexity will be removed.

**Comment by MonsieurNicolas** [comment]
@vogel : I've discussed this offline with @graydon and the conclusion was that we should remove support for arbitrary jumps post the initial one.

The trade off being made here is: either we remove the jump functionality as originally discussed, or keep the jump capability. The problem with keeping the functionality around is that the code will basically "rot" in place as that particular configuration ends up being very niche: most people either run a validator for the purpose of supporting something like Horizon (no gaps allowed) or run a full validator that also supports history (no jumps allowed either).

The assumption is that most of the complex "inner logic" doesn't get touched (we still need to "diff" bucket lists for example): on the other hand, we can simplify interfaces (which parameters get passed around) and tests.
