### ISSUE TITLE
audit `unsigned` types in xdr

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1960]
We've made those changes in the past, but we've missed a few places:
in a nutshell, we should not use unsigned types where we can as this causes problems in both SQL and languages that don't support unsigned integers.

Example:
`offerID` is `uint64`

Just like sequence number in the past, the change should be safe:
it may require some minor SDK changes, and the "on wire" format is compatible (as we don't have values that would overflow the signed range).

**Comment by marta-lokhova** [comment]
Okay, some findings:
1.  `OfferID` should be okay to change I believe; we already handle `> MAX_INT64` case in core, and all current valid offer IDs should still be valid.  There are several places that need to reflect that:
* ManageOfferOp.offerID
* ClaimOfferAtom.offerID
* Any `> MAX_INT64` checks should convert into ` > 0`, and unsigned to signed conversions must be removed

2. TimePoint is uint64, and is used in `TimeBounds` and `StellarValue.closeTime`. We currently store ledger's close time in the DB (without proper unsigned-to-signed conversion, by the way, which happens to be ok, but in theory can blow up, so it should get fixed). While it looks like SDKs do not directly use MAX_UINT64, any transactions with `maxTime > MAX_INT64` would become invalid. Perhaps that is fine though, since Horizon can't ingest anything above signed limit anyway (fixed after the latest crash). 

3. `AccountEntry.numSubEntries`: I think should be also ok to change - we already perform a check and throw if it's over the limit `MAX_INT64`, so any valid transactions would stay valid. For this, we'd need to update our checks similarly to how it's done for offerID.

4. I noticed that fee types are not consistent across the board. `Transaction.fee` is uint32, while `TransactionResult.feeCharged` is int64, but feeCharged = fee anyway. I think it's be good to have them consistent, and it seems like only light changes to the SDKs are required. 

5. This is probably minor, but memo ID can be made signed - we don'd store it, Horizon stores a string, but it might make life easier for SDKs that don't support signed ints (Java SDK has a whole class that implements MemoID...)

6. I noticed that any field that represents `ledgerseq` is consistently unsigned, and it seems like changing it to signed will be painful, as it's used in many places, so probably not worth the effort at this time.

**Comment by MonsieurNicolas** [comment]
Cool.

`OfferID` changes seem good.

`TimePoint` : yeah we can't change it easily as we don't know if there are presigned transactions with high number in there

`AccountEntry.numSubEntries`: no reason to change it, people will run out of memory/XLM before hitting that limit

fees: the right change would be to have `Transaction.fee` be an int64, but that's a change in envelope. Changing `TransactionResult.feeCharged` to be an `uint32` would potentially introduce overflow bugs similar to what we had in core at some point (because in C++ `uint32 * uint32` is an `uint32` not a `uint64`)

`MemoID` - I don't know which ID that is, there is a `Memo` union that only has 5 possible values

`ledgerSeq` - I agree, not worth changing as ledger `INT32_MAX` is estimated to be over 300 years from now
