### ISSUE TITLE
Figure out how to instrument performance critical areas

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#1979]
It is currently hard to extract detailed information about utilization patterns and performance hotspots in the stellar-core transactions subsystem. An example question that one might ask is, "On average, how many ledger entries of a given type are loaded when applying a given operation type?"

In order to facilitate data collection on these topics, we can add logging in `LedgerTxnRoot` which indicates how it is interacting with the database/cache. This logging should be in a new logging namespace, perhaps called "TxDetail", along with some existing logs which give information about the transaction set, transaction, and operation being applied.

**Comment by MonsieurNicolas** [comment]
We've decided to not do this for now: it's unclear if logging is the right approach as logging adds tons of overhead. Solution might be something like "point of interests" as discussed in #2386 (sadly what is described there may not be what we want, see discussion in the PR)

**Comment by MonsieurNicolas** [comment]
Right now, when trying to understand perf critical areas, we only have the following options:
* use a profiler
  * while profilers are very good at identifying choke points in call trees,
  * they are a very poor choice when trying to identify outliers caused by certain inputs, for example, if 1% of the calls to a function are ten times slower than others, the "context" for those 1% will be lost completely (and won't be visible in profiles).
* add new metrics
  * metrics can help extract percentiles (now that we have sliding windows) for certain functions
  * issue there is that there can be an explosion in the number of metrics, adding a lot of overhead to the system (for example, right now we have the execution time of operations, but we'd need 10x more metrics for operations if we wanted to have the break down per operation type)
* add new logs
  * logging is the most flexible option as it allows to add arbitrary context to log lines
  * there are many problems with logging though
     * logging is expensive and adds a non trivial amount of latency (right now system wide TRACE is unusable because of this). In addition, log files become so big that the overhead of managing those files becomes a huge tax on the system as well.
    * log format is "ad-hoc", so trying to aggregate/extract log lines pertinent to certain call paths is not possible right now.

There was an attempt at introducing a new way with #2386 but there are too many issues with that approach (it's a new parallel instrumentation, is not cross platform and requires a lot of maintenance).

I think we need to define a strategy when it comes to performance analysis:
* we need to have "always visible" (metric) aggregate signals that point to issues in aggregate (P99 is probably enough)
* when trying to understand what the underlying issue is with those issues, there should be a low overhead way to get to "the next level of detail"

I am not sure we need super complicated machinery to meet those goals:

in the past I worked on system that would attach arbitrary "tags" to a context object (context would be created at the "top level" of the stack), used as a way to decorate logs.

We may be able to take this idea and apply it to metrics:
by default, we would not tag anything, but we can (via the http endpoint) enable certain tags.

When updating metrics, we would in addition to updating the "global"(tagless) metric, also update the tagged ones.

So with my previous example, enabling the "operation type" tag, would cause all calls to `someMetric.update` to update not just the normal metric associated with `someMetric`, but also new metrics with the tags, in this case `ledger.operation.apply` would be updated but also `ledger.operation.apply.op=1` (payment).

When multiple tags are present, at a minimum we'd have the aggregate per tag, but could add a way to also aggregate on multiple tags (controlled by the http endpoint, it's just a matter of keeping track of the aggregates that we want to update).

There might already be libraries that do this, if not this seems to be fairly easy to add to out fork of medida (or better, with a wrapper on top of it).

**Comment by jonjove** [comment]
@graydon Do you think Tracy might help with questions like this? Or do you think it's not really the tool for the job?

**Comment by graydon** [comment]
@jonjove Absolutely. There are maybe 4 things to note here:
  1. If you're trying to differentiate zones in the trace that have a relatively small (dozens-to-hundreds) set of possible values -- i.e. values that you're interested in grouping by for aggregate-analysis purposes -- then you should probably just attach the values to the zones in question using `ZoneValue(int64)` or `ZoneText(char*)` annotations. This will show up as annotations and the zone inspection dialogs will allow grouping and subsetting based on them. There are examples of this already in stellar-core's code.
  2. If you're trying to record "one time" event-detail messages that you just want to inspect in the timeline as they pass, but they're not going to be meaningfully grouped or anything, you should probably emit a `TracyMessage(char*)` which will just show up as a point-in-time message in the timeline and the messages log. There are not currently any uses of this in stellar-core but it's very straightforward.
  3. If you want to watch some numeric value that varies at a relatively high frequency and across many values (so is less appropriate for `ZoneValue`) you can plot it like a metric underneath the timeline using `TracyPlot(char*, int64)`. There are instances of this in stellar-core presently.
  4. We do not do this presently, but we can if it matters: tracy supports a way for the client (stellar-core) to present a bunch of "parameters" to the user operating the server (GUI), using `TracyParameterRegister` and `TracyParameterSetup`. These appear in the form of named numbers or booleans in the GUI that the user can adjust to change how the collection is proceeding, interactively; they are communicated back to a client-provided callback that we can do whatever we want with in stellar-core. They are there to allow the analyst to dynamically turn on or off subsets of instrumentation, if there are some that are particularly egregious in the volume of data they produce or such.

**Comment by MonsieurNicolas** [comment]
I think we can close this issue now that we have Tracy integration @jonjove

**Comment by jonjove** [comment]
Agreed.
