### ISSUE TITLE
continue to discover peers even when node is full

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1990]
Right now when a node is full and a new peer connects to it, we just drop that new peer.

We should also learn its IP address as to see if we can promote it to an outbound peer (we can learn new IPs via the "peers" command anyways, so it doesn't bad).

This is especially useful when starting up a clean node that happens to be very popular (like our testnet nodes), as this allows us to discover other good validators that accept new connections (and connect to them).

**Comment by vogel** [comment]
Accepting inbound connection is done in `OverlayManagerImpl::addInboundConnection`. At that point we don't know `PEER_PORT` of inbound peer (as we only learn that after receiving `HELLO` message). If at this point our pending inbound list is full, we cannot store that peer in our database (we could always assume that is uses default port, but I'm not sure if we should do that).

When we have enough pending slots, peers get to exchange messages with each other. First one of the messages is of course `HELLO`, which gives us remote `PEER_PORT` value (`Peer::recvHello`). If everything with certs, network passphase, bans and port is OK, first thing we do is to store peer data into database (`Peer::updatePeerRecordAfterEcho`). Only after that we check for other data (preferredness, number of authenticated slots etc) in `OverlayManagerImpl::PeersList::acceptAuthenticatedPeer`.

So if the problem is with overabundance of inbound pending peers, maybe the proper solution would be to increase MAX_PENDING_CONNECTIONS setting.

**Comment by MonsieurNicolas** [comment]
OK, so as we call `updatePeerRecordAfterEcho` we should be try to connect back to that peer at some point, right?

What would stop us from attempting to promote a peer in this situation?

Could it be then that we don't try to promote when there is a pending connection to that other peer (that keeps trying to connect to us)?

**Comment by vogel** [comment]
Lets see. When someone tries to connect to us, there are several possibilities:
- we have free slots for inbound connections, so we just connect
- we have no free slots for inbound connections, but we have free slots for pending inbound connections (for preferred peers for example), so we connect and exchange hello messages (also we give that peer some other peer addresses)
- we have already a lot of inbound pending connections, and cannot accept any more; in that case, there is nothing we can do (well, one possibility: store that IP with default peer port and try to promote that one, even if the address is not valid)

In the first and second case, `updatePeerRecordAfterEcho` is called. For inbound unknown peers it adds new entry to `peers` table with `REMOVE_PREFERRED` update, which sets its type to `INBOUND`. So we have that peer in database.

Then in each `tick` of `OverlayManger` that peer can be promoted. To be promoted several factors must play out:
- connecting to preferred peers should not take all of remaining outbound pending slots (pendingUsedByPreferred < availablePendingSlots) - that needs to be checked (I expect it to always be true, as TARGET_PEER_CONNECTIONS should be always less that MAX_OUTBOUND_PENDING_CONNECTIONS, and before each tick all pending peers should either authenticate or timeout)
- availablePendingSlots > 2 later, so we are not using remaining slot to get one more outbound connection (that may be false more often, I'll check that)
- that peer must be selected by RandomPeerSource

I'll now check it all of that behaves as I would expect.

**Comment by vogel** [comment]
It all looks good. I think I need to see configuration of peer that has problems with promoting. Maybe its number of allowed outbound pending connections is too low?

Also promotion should work when peer is trying to connect to us when we are trying to promote it. Promotion is done in `updatePeerRecordAfterEcho`, which is called before we check for already-connected peers.

**Comment by MonsieurNicolas** [comment]
I don't think this is problem now that we have the new code for determinining if we're connected to a recent consensus round
