### ISSUE TITLE
Large merges and stalled checkpoint publication

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#2037]
Reported https://stellar.stackexchange.com/questions/2359/huge-temporary-bucket-files-created-and-then-destroyed-on-all-cores-is-this-n

Possibly one or two different bugs:

  - We might be resolving pending merges before uploading and then failing to save the resolved state, requiring us to re-resolve if the upload fails and we have to retry.
  - We might actually be _causing_ a publication timeout (thus publication work retry at a higher level) if resolution of pending merges takes too long. If so, combined with previous case this might cause total cessation of publication / endless accumulation of pending publications.

Investigate both!

**Comment by MonsieurNicolas** [comment]
note that there is a lot of good information on this in #1746

**Comment by MonsieurNicolas** [comment]
(it's on a private network with it seems very large buckets)

**Comment by fuzzyami** [comment]
@graydon, hello again. I would love to help you solve this issue in whatever way I can. Please note:
1. the network on which we've seen this issue is based on v9.2 and running 7 cores.
2. I do not believe this is a configuration issue. Our config is very simple (and stable). we publish to S3 and there are no special flags or anything fancy.
3. this issue started happening simultaneously on all cores. we've since been able to overcome it by capping the publishing time to ~10 seconds and thus eliminating the queue of checkpoints, which seems to have fixed it. we've since reverted back to the original core and it has not reproduced.
4. We've deliberately left one core in a "broken" state. its synced, but has an enormously long queue ATM. Perhaps I can provide you with logs from that core? any particular log level you'd like?

**Comment by marta-lokhova** [comment]
Quick note on this one: publish does not timeout, since snapshot resolution technically does not fail, but retries forever until success.

**Comment by MonsieurNicolas** [comment]
@marta-lokhova is working through potential design changes that should mitigate this

**Comment by MonsieurNicolas** [comment]
This should now be fixed
