### ISSUE TITLE
Stellar core unable to recover from testnet reset

### ISSUE THREAD

**Issue by khelle** [stellar/stellar-core#2066]
Since Stellar introduced periodical resets of the testnet network, it should also introduced some method to recover from those testnet resets. Right now the only way to solve it is to manually reset buckets and database and restart service which would not be that problematic if worked 100% of the time. Unfortunately most of the nodes on network stays for a long time on old blockchain making it unable to properly connect. 

Half a day passed since last reset and my testnet nodes were still unable to catch up. I am purging their databases and buckets every hour and nothing helps. Each time they get the old blockchain from some random peers.

Is there any kind of workaround to force it somehow on good chain or not yet?

**Comment by MonsieurNicolas** [comment]
There was a problem during the reset and testnet was down for about 5 hours, I think you hit that.

For making this better the solution is to change the network passphrase (already supported by core) but this is a much broader (SDKs, websites etc) problem. I know folks have been gathering feedback on the various channels (like keybase).

I’m closing this issue here as this is non actionable at the core layer.
