### ISSUE TITLE
Ensure that metrics/logs that track history archives on failure are actionable

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2329]
This replaces issue #1263 : 
we need to make sure that we properly compute metrics for each archive so that an operator can remove/check that a specific "gettable" archive is configured properly.

Right now, I *think* that we don't really distinguish:
* archive is having a real problem (fatal error)
  * not up to date (stale archive)
  * archive is missing certain files that should be there
  * archive contains corrupt files
* runs into some transient "likely" error
  * attempt at downloading files while they're being uploaded by the other validator (occurs often when trying to catchup to the latest checkpoint)

Tagging for discussion until we define the exact scope of the work:
it could be that we just need better/more consistent logging.

**Comment by marta-lokhova** [comment]
Ok, after a bit of a code audit, a few ideas here. It seems like the best thing for us to do is to ensure that failures/corruptions are understood at the node operator level, so that they can take some action.

### Metric granularity
Currently, there are three ways we expose archive problems: the cryptic `history_failure_rate` in `info` endpoint, which aggregates all history metrics for all archives (not super helpful, since we can't even tell which archive caused problems), logging and archive metrics. The issue with metrics is that they might be too coarse. For example, each archive has "success" and "failure" metrics, which aggregate both catchup and publish. It might make more sense to split it into two categories: "read & validate" (catchup) and "write" (publish). Additionally, we do not distinguish failure types (stale, missing files, corrupt), so we could add those metrics as well.

### Pointing out the exact problem
I think the node can reason about why it's having problems with a specific archive by looking at where the error occurred in download->verify sequence plus the validity of archive header files (HAS). 

For example:
1. HAS claims it has ledger N, but download of it failed --> missing file
2. HAS claims it has ledger N, but verification of it failed (download succeeded) --> corrupt file
3. HAS is too far behind (say, 10 checkpoints) the current ledger from consensus --> stale archive
(We'd need to think here what to do with offline catchup)
4. Transient error due to an ongoing upload: from what I see in the code, all the checkpoint files are uploaded before checkpoint header + archive header are uploaded, so the transient errors we would see should be "archive does not have the checkpoint you're asking for" (as opposed to "some files for this checkpoint are missing"). In this scenario, we don't mark the archive as stale until it reaches the gap discussed in 3. So, in a way, we consider the archive "still publishing and this valid" for some number of checkpoints before we give up on it. 

### Surfacing issues
* As we improve metrics, we can make tweaks to the `info` endpoint. For starters, I'm not sure if exposing `history_failure_rate` is actually helpful, since it's not clear what it means and what archive to blame. Instead, I propose we have a small map with each archive and a short message of what the node has gathered while interacting with this archive. For example:
```
[
     "sdf1" : "Potentially corrupt: bad file ledger-0000443f.xdr",
     "sdf2" : "Potentially stale: last published checkpoint 0000443f",
     "sdf3" : "Ok",
]
```
Of course, this is a very limited view on the archives, since it gathers info on archives only when the node interacts with them. So, for example, if the node is always in-sync, we'd never find out that some ledger range in the archive is corrupt. But at least this will give some clues to node operators when problems do happen. 

* While the info endpoint information should be very brief, ideally we'd provide more details via logging (i.e. potential remedies for the problem)

**Comment by marta-lokhova** [comment]
@MonsieurNicolas Do we still want this in 14.0.0? There is a PR open, which needs to be resurrected in case we want to merge it.

**Comment by MonsieurNicolas** [comment]
no, I am moving this to 14.1 for now
