### ISSUE TITLE
cleanup and merge orderbook not crossed invariant

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2417]
https://github.com/stellar/stellar-core/pull/2210

**Comment by MonsieurNicolas** [comment]
this implements one of #2884

**Comment by rokopt** [comment]
A couple notes/questions:

- In the current #2210 , the new invariant is compiled in and enabled when and only when we compile for fuzzing (`FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`).  Should we instead do this as we did the best-offer debugging (#2944 ) and compile it in when and only when extrachecks are enabled, and use a new `Config` parameter to make sure it's only used during `stellar-core fuzz` and `stellar-core test` (not, for example, `stellar-core run` or `stellar-core catchup`)?
- The invariant as is can fire incorrectly because it doesn't know about passive offers.  I think that the right fix is to test `if (lowestAsk == highestBid)` in `checkCrossed()` and in that case to fire the assertion only if there is at least one non-passive ask at that price and at least one non-passive bid at that price.  But please let me know if that doesn't sound right!

**Comment by rokopt** [comment]
> * In the current #2210 , the new invariant is compiled in and enabled when and only when we compile for fuzzing (`FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`).  Should we instead do this as we did the best-offer debugging (#2944 ) and compile it in when and only when extrachecks are enabled, and use a new `Config` parameter to make sure it's only used during `stellar-core fuzz` and `stellar-core test` (not, for example, `stellar-core run` or `stellar-core catchup`)?

After further thought, I realize that we can't do that with the order-book-not-crossed invariant:  unlike other invariants, it maintains state (`mOrderBook`) from one call to `checkOnOperationApply()` to another.  There's no provision for that in `InvariantManager`, and in particular it won't work because the order-book invariant won't know if the transaction whose operations had been applied were later rolled back.  Consequently, it might think (in its `mOrderBook`) that there's an offer present which isn't, so it might spuriously believe that the order book is crossed when some new offer appears that _would_ have crossed with that offer if it really still existed.
