### ISSUE TITLE
Unexpected fee surge pricing (Version: 12.3.0, testnet)

### ISSUE THREAD

**Issue by orbitlens** [stellar/stellar-core#2428]
## Issue Description

@Alon [reported](https://stellar.stackexchange.com/q/2974/366) strange fee surge pricing on the testnet. The [ledger 171583 contains only 3 transactions](https://horizon-testnet.stellar.org/ledgers/171583/transactions) with a single operation each and despite the fact that base fee is 100 stroops, the network charged 100000 stroops for every transaction. The same behavior is spotted on the ledger 171589. 

Checked:
- There are no failed transactions that could possibly contribute to the fee surge.
- Mempool seems empty, there were no transactions in the next few ledgers following 171583. Previous ledger contains a single transaction with fee 100 stroops.
- It's not a Horizon parsing issue, raw tx results XDR from testnet Core db shows that there were only 3 transactions and actual fee charged amount is 10000 stroops.

## Steps to Reproduce

- https://horizon-testnet.stellar.org/ledgers/171583/transactions
- https://horizon-testnet.stellar.org/ledgers/171589/transactions

## Expected Result
According to [CAP-0005](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0005.md) the actual fee charge should be 100 stroops instead of 10000.

## Environment
* Core 12.3.0
* Stellar testnet

**Comment by jonjove** [comment]
Interesting report, had to review both the proposal and the actual implementation. From CAP-0005:
> 6. if count_ops(txSet) > max(0, ledgerHeader.maxTxSetSize-100)
surge pricing in effect

On the test network, `maxTxSetSize = 100` so we can conclude that surge pricing is always in effect on the test network. I'm not sure if it is desirable to have surge pricing _always in effect_ on the test network since it is rather different from the production network. @MonsieurNicolas perhaps it would make more sense to have `maxTxSetSize = 125` or `maxTxSetSize = 150` so that there is sometimes surge pricing and sometimes no surge pricing.

**Comment by orbitlens** [comment]
Is there any special reason for turning on surge pricing when ledger capacity has not been reached? I mean the `ledgerHeader.maxTxSetSize-100` condition? Why not just `if count_ops(txSet) >  ledgerHeader.maxTxSetSize`?

**Comment by jonjove** [comment]
Well `count_ops(txSet) > ledgerHeader.maxTxSetSize` never happens (if it did, then `maxTxSetSize` would not in fact be the max transaction set size). So, if I remember correctly, the argument for `maxTxSetSize - 100` was that anything above that amount indicates that the first transaction which was excluded could have brought it over `maxTxSetSize`. But the first transaction that was excluded isn't known, so we can't do any better than that in general. Does that make sense?

**Comment by orbitlens** [comment]
@jonjove Yeah, I specified incorrect condition.
 
I meant something like `if !heap.empty() then surge pricing in effect` at step 6. In that way surge pricing takes effect only when we have at least one transaction left in the mempool. Otherwise for, say, `maxTxSetSize=200` we'll always experience surge pricing even if we have only 100 operations in total across all transaction candidates for the current ledger. The testnet example demonstrated the edge case of this behavior.

**Comment by jonjove** [comment]
I don't think that works, because nodes don't (in general) know the transactions that were excluded. The nominating node knows what transactions were excluded because that node crafted the transaction set from its mempool. But when voting on or applying a transaction set crafted by another node, other nodes don't know what transactions were excluded because the transaction set wasn't crafted from their mempools. 

Here's an example taking your approach. Node 1 crafts a transaction set containing 95 operations and has nothing left in its mempool. Node 2 votes for this transaction set, but has 5 operations left in its mempool. Node 3 also votes for this transaction set, but has 10 operations left in its mempool. The transaction set is accepted, and subsequently applied. From the perspective of node 1, there shouldn't be surge pricing. From the perspective of node 2, not every transaction it wanted to include was included but there still shouldn't be surge pricing. From the perspective of node 3, not every transaction it wanted to include was included and there should have been surge pricing. So who's right? Everyone needs to agree.

The way I think of this is that the state of the mempool isn't controlled at the protocol level. You can't rely on it at all for things that every node needs to agree upon, such as the fee.

**Comment by orbitlens** [comment]
Oh, now I grasp the whole idea of it. And the reason behind the magic number 100 - it's max ops per tx, so the condition actually guarantees that the crafted txset has a capacity to accommodate at least one more tx. Thanks for the explanation, @jonjove!

However, based on your example the behavior will be similar for the existing logic. For instance, on the pubnet we have `maxTxSetSize = 1000`. Node 1 crafts a transaction set containing 890 operations and has nothing left in its mempool. Node 2 votes for this transaction set, but has 50 operations left in its mempool. Node 3 also votes for this transaction set, but has 150 operations left in its mempool. The transaction set is accepted, and subsequently applied. From the perspective of node 2 and node 3, there should have been surge pricing.

Am I missing something here?

**Comment by MonsieurNicolas** [comment]
@orbitlens you've been thinking about it from the point of view of how to craft a transaction set, the important bit here is when a validator receives a transaction set it has to be able to determine if surge pricing was active or not - it doesn't use its own mempool to determine this.

On pubnet, if the number of operations in a txset is more than 900, we consider that surge pricing was in effect (we assume that it stopped there because `!heap.empty()`).

See https://github.com/stellar/stellar-protocol/blob/master/core/cap-0005.md#computation-of-the-associated-effective-base-fee

**Comment by MonsieurNicolas** [comment]
closing as this is not a core bug
