### ISSUE TITLE
Node should start nominating if it sees that it's on the right ledger

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2542]
Right now we decide to nominate on startup only based on `FORCE_SCP`.

But if the network is on the same ledger, the local node should be able to start nomination as well.

This would allow (alongside #2081 ) for a node to fully participate to consensus on restart.

The tricky question is deciding what "on the same ledger" means:
it's possible the network is stuck nominating the same slot, but it could also be that the network moved on to a different slot.

A possibility could be to deprecate `FORCE_SCP`, but this could cause other problems in catastrophic situations (ie bad network fork) - this needs to be analyzed (we added this early on before validating SCP). I suspect it's not needed anymore.

We could go with a less aggressive stance: `FORCE_SCP=false` can trigger if we don't see messages from our quorum set at a later slot (this criteria should take into account the possibility of dealing with byzantine nodes so it's really a small subset of nodes that could be ahead, like a v-blocking set).

**Comment by marta-lokhova** [comment]
Re: network fork analysis

Note: I think that when we do have quorum intersection (optimal safety), removing force_scp should not cause problems (and probably even make things better, i.e. better liveness without compromising safety)

The rest of the analysis is about various network fork scenarios with and without force_scp (so no quorum intersection)

1. part of the network (a subset of high quality nodes to bootstrap the network, for example) restarts with force_scp=true, there are two possibilities if the rest of the network has force_scp=false:
* nodes will get stuck (total absence of quorum intersection, meaning a completely disjoint group of nodes)
* nodes will wait to see a quorum set agree, then proceed or get stuck/die (not sure which exactly, need to look closely at the code) if their state previously diverged.
  * the topology I'm referring to here is such that nodes are connected, but not sufficiently, so due to thresholds a fork is possible
  * However, because of the lack of quorum intersection, safety of those nodes is compromised anyway (so they can diverge in the subsequent ledgers)

2. the network was re-started, but now everyone is nominating right away (so no one is waiting to see consensus)
* parts of the network can diverge on the very first ledger after the restart (for any quorum configuration that does not have quorum intersection), so multiple forks could close ledgers independently (though, some nodes may get stuck/die if they receive contradicting messages; a lot here depends on timing and message ordering)

So from what I can tell, force_scp maybe helps a bit (for example, when the nodes get stuck instead of diverging, though I don't know if a completely disjoint topology like this is realistic), but at the same time we have the same "nodes diverge due to quorum misconfiguration" issue.

**Comment by MonsieurNicolas** [comment]
That sounds about right.

> So from what I can tell, force_scp maybe helps a bit (for example, when the nodes get stuck instead of diverging, though I don't know if a completely disjoint topology like this is realistic), but at the same time we have the same "nodes diverge due to quorum misconfiguration" issue.

Yes it helps a bit if all validators were stopped, but this seems like the less likely scenario. The more realistic situation is that nodes don't get restarted and the fork is live anyways.
If operators are actively restarting their nodes in this situation (where force_scp would potentially help), it probably means that there is already broad communication that there was a quorum intersection failure and a gradual restart of nodes (with updated quorum set configuration) needs to be coordinated anyways.

As long as validators don't contradict themselves (ie, always restore their SCP state), this should be a net positive on the liveness front.

I think it can be useful in some situations to *not* start "in sync" (as this implies to timeout due to "out of sync").
So, as far as next step, maybe what we can just do is change the default for nodes that are configured as validators (for watcher nodes, we should continue to have it set to `false` by default, so the default should really be `FORCE_SCP = NODE_IS_VALIDATOR`) and add a `wait-for-consensus` option (that is the opposite of `force-scp`)?

Also, this allows to have a smooth transition (we have to keep the `force-scp` command as a no-op until all images and acceptance tests stop using it).
