### ISSUE TITLE
Bad feebump signature gives result code `tx_insufficient_fee`

### ISSUE THREAD

**Issue by Synesso** [stellar/stellar-core#2590]
stellar/go#2353 # What version are you using?

```
  "horizon_version": "1.4.0-d535a7970fa8f82f31d00eff35d442b23add9ba7",
  "core_version": "stellar-core 13.1.0 (469b2e70dec29ade2c57d39bc9db129579e63207)",
  "network_passphrase": "Test SDF Network ; September 2015",
  "current_protocol_version": 13,
  "core_supported_protocol_version": 13
```

### What did you do?

Submitted fee bump transaction with bad fee bump signature.

https://laboratory.stellar.org/#txsubmitter?input=AAAABQAAAABkRWYVA4NxmiZUibHxDNXohsINnVWEc7tfktZd3rrrUQAAAAAAvrwgAAAAAgAAAAB5M7UAjmmALSznmFU8nqnSS1TOIRgHWTzeOhfLlu4DHACYloAADLwrAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAGRFZhUDg3GaJlSJsfEM1eiGwg2dVYRzu1%2BS1l3euutRAAAAAAAAAAABMS0AAAAAAAAAAAGW7gMcAAAAQJPj50gRrhyvuMRHtFhT3Lcjnf%2BNCx1XGqYdR%2BmwrzXjfQGfCqL40H5CoOlzexMzsPWcMFcsJpGD74azLmrPyQMAAAAAAAAAAd6661EAAABAeCxe6mF833titr0DlatXp7CAGqqkAmQvj2kxMMEjWAVN%2F91mYNaagFBysFRLp8Ra%2BbLdFf80dXPkVZGZhAKaCA%3D%3D&network=test

### What did you expect to see?

Error denoting bad signature.

### What did you see instead?

Error denoting insufficient fee.

```
extras.result_codes:
 {"transaction":"tx_insufficient_fee"} 
Result XDR:
 AAAAAAAAAMj////3AAAAAA== 
```

**Comment by jonjove** [comment]
Thank you for the report! This is correct, and @bartekn's explanation is exactly right. The same also applies for normal transactions: fees are checked before signatures.

**Comment by Synesso** [comment]
To be clear, is the fee of 12,500,000 stroops insufficient?

**Comment by Synesso** [comment]
I think I understand. The message is corrupt, so all bets are off as to behaviour. That the laboratory manages to differentiate the bad part of the message from the good is just luck.

**Comment by bartekn** [comment]
I think this can the [Replace-by-Fee](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0015.md#replace-by-fee) case. The bumped fee must be 10 higher than inner tx fee so in your case 100 000 000 stroops.

**Comment by jonjove** [comment]
@Synesso The message isn't corrupt. The order of the error codes is somewhat arbitrary but it is well defined. The fee is indeed insufficient, but _not_ because of replace-by-fee as @bartekn suggested. This is actually caused by the second paragraph in this section https://github.com/stellar/stellar-protocol/blob/master/core/cap-0015.md#fees.

What you submitted was a "down bump" where you inadvertently tried to reduce the fee-rate (which is the effective fee per operation). Your inner transaction has 1 operation and fee 10,000,000 for a fee-rate of `10,000,000 / 1 = 10,000,000`. But your fee bump has 1 operation, plus 1 because it is a fee-bump meaning 2 effective operations, and fee 12,500,000 for a fee-rate of `12,500,000 / 2 = 6,250,000 < 10,000,000`.

**Comment by Synesso** [comment]
Oh, got it. Thanks again.

**Comment by Chidiebere95** [comment]
Use this to get the network base fee 
`const fee = await server.fetchBaseFee();`
And add it as params to the fucntion

`const transaction = new StellarSdk.TransactionBuilder(senderAccount, {
      fee,
      networkPassphrase,
      memo: new StellarSdk.Memo('text', 'test memo...'),
    })`
