### ISSUE TITLE
move to "real" json for "dump-xdr"/"print-xdr"

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2681]
An option `--json` was added to `dump-xdr` some time ago as to use proper json when using subcommands.

This was partially added: the `print-xdr` command doesn't have this option.

We should:
* remove that option and move to using that real "json" formatter the default behavior for both `dumpt-xdr` and `print-xdr`
* ensure that there are the right overrides when dealing with `MuxedAccount`
  * it looks like the json formatter doesn't have the override that "xdr_printer" has `xdr_printer(MuxedAccount const& muxedAccount)`

NB: I did a quick performance test, calling `dump-xdr` on a bucket file, and there doesn't seem to be any difference in runtime between the json and the old-style version.

**Comment by MonsieurNicolas** [comment]
I think we should add a new option `--compact` to those commands, that would cause to pass in `cereal::JSONOutputArchive::Options::NoIndent()` as an option to `cereal::JSONOutputArchive` : this speeds things up by over 50% and scripts only need that.

**Comment by jonjove** [comment]
I don't think this issue covers quite everything that #2543 covered. #2543 was partially directed at other uses of `xdr::xdr_to_string` (such as logging in an invariant failure). The `JSONOutputArchive` functions will serve that purpose well, but we should

a. Move those functions into a utility header so they can be accessed wherever they are needed
b. Stop using `xdr::xdr_to_string` everywhere since it doesn't handle custom multi-line output well

(a) should definitely be part of this issue. (b) can be done in a separate issue if you prefer, I'm indifferent.

**Comment by MonsieurNicolas** [comment]
Yeah that sounds right. This issue can track both. When we replace `xdr_to_string` we need to use the version that indents.

**Comment by jonjove** [comment]
Part (b) in my last comment hasn't been addressed yet. Should we reopen this?

**Comment by MonsieurNicolas** [comment]
ah yes you are right - forgot we wanted to do this sweep.

OK, I am re-opening it.

I also noticed that we left some `xdr_printer` functions in `dumpxdr.cpp` that are probably not used.
