### ISSUE TITLE
Consider using a randomized hasher for checked builds

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2809]
Every few months we run into issues (usually in tests but that can happen in production code), where code makes hidden assumptions on the iteration order for `unordered_map`.

Most recently in #2808 (in the past we had comparisons between two different `unordered_map` that would "usually" work).

I prototyped the change to increase the chance of detecting this kind of problem:
https://github.com/MonsieurNicolas/stellar-core/tree/randomHasher

I don't know if there is something better we can do; opening this issue for discussing for now

**Comment by graydon** [comment]
Yeah. This feels to me like it's fairly similar to our nondeterminism tension elsewhere: we want the program to be deterministic run-over-run in testing, but we also want regular slow (eg. daily or so) churn in that determinism over anything that's going to be "much more nondeterministic" when running in production, so we don't have test/prod mismatches or things that only work because of a fluke in their determinism seed.

(Which, I guess, is a long-winded way of saying "I think you're probably doing the right thing in that change")

As a more constructive note: I'd like at some point to have a go at replacing all our hashtables and hash functions with faster ones. We lose a fair amount to the stdlib's one, as far as I can tell. But maybe this change isn't the time or place for it.
