### ISSUE TITLE
logrotate trashes files

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2867]
It looks like logrotate (the tool, not the endpoint) causes unexpected behavior with spdlog.

When a file gets rotated, it looks like the file is partially reset and appended to:
The log file after log rotation contains a lot of `0` bytes at the beginning of the file (exactly "log file size" before rotation), followed by the actual log content.

I am not sure what is going on - it looks like spdlog is fseeking to some cached offset, causing the 0 bytes to be added?

Note that this is using the `copytruncate` option of logrotate - that is supposed to be the "universal" log rotation.

### System information

Ubuntu

log rotate config file : `/etc/logrotate.d/stellar-core`
```
# Keep 7 days worth of logs
/var/log/stellar/stellar-core.log {
  hourly
  missingok
  rotate 72
  compress
  notifempty
  copytruncate
}
```

**Comment by graydon** [comment]
I haven't been able to reproduce this locally. I'm on Ubuntu 20.04 LTS / Linux 5.4.0-58, whereas it was reported on Ubuntu 16.04 LTS / Linux 4.4.0-1079-aws. I'll attempt to build on a suitable VM next.

**Comment by graydon** [comment]
Unable to reproduce on 4.4.0-1117-aws (which is a slightly later build than on the reported system -- but the one you get when you instantiate a fresh 16.04 LTS AMI)

**Comment by graydon** [comment]
Ok, reproduced: requires stellar-core version 606afede2ecd1c42a19f2e6103339747164418f4 (fails on any version of linux -- not kernel-specific) and is apparently also "fixed" by my last logging change a3ded40ca04cd9a2444c04e4f48311917f164a3f .. I will look into how/why next!

**Comment by graydon** [comment]
Ok, I believe this relates to the `truncate` flag: when it's set, a file descriptor is opened in `"wb"` mode, otherwise in `"ab"` mode (translating to `O_APPEND`) -- which causes the fd to always atomically seek-to and write-to the end of the file, wherever the write-pointer was seeked to (and _even if_ it was truncated after the last write). See: https://unix.stackexchange.com/a/475621

So .. I think the solution here is:

  - Always set the truncate option to false, even when processing the logrotate HTTP endpoint
  - Implement the logrotate HTTP endpoint with a _manual_ truncate between `deinit()` and `init()`

I'll give this a try tomorrow. Out of energy for tonight; but at least I think this explains the behaviour. `logrotate(1)` just assumes everyone writing a log opens it in `O_APPEND` mode.

**Comment by graydon** [comment]
Fwiw I opened https://github.com/gabime/spdlog/issues/1793 upstream and the maintainer is happy to take a fix, so I might file a PR with a fix there as well.
