### ISSUE TITLE
logging truncates log files

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2868]
When we reopen log files (on startup or logrotate), we truncate the file.

This is bad because if core crashes or gets restarted, it basically deletes its log file.

We should be appending instead.

It looks to be a 1 line change as we're passing `/*truncate=*/true` when we create the file sink.

**Comment by graydon** [comment]
easylogging also truncated on logrotate, but not on startup (if you use a fixed filename -- of course none of this is an issue if you're using the default timestamp-derived filenames since they always give you new log files).

I will change it to truncate only on logrotate, to match old easylogging behaviour.
