### ISSUE TITLE
Add an upper bound to the number of ledgers tracked in memory while catching up

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3157]
When a core node close ledgers while catching up, it accumulates ledger information in `CatchupManager`.

The problem is that if the "catchup" being performed takes a "very long time" (like what happens when running with `CATCHUP_COMPLETE=true`), then the memory utilization can become arbitrary large.

Instead we should only keep a few more ledgers in addition to the "tip" of recent ledgers enough to re-trigger catchup.

**Comment by MonsieurNicolas** [comment]
(Assigning to Hide for later)

**Comment by hidenori-shinohara** [comment]
I started looking into this, but I'm going to move onto another bug for now as there are two bugs for v18.0.0.

For future reference:

One approach that'd achieve this is to pop elements from `mSyncingLedgers` in some condition (e.g., if it has more than `N` elements) However, that'd create a gap between `mSyncingLedgers` and the last closed ledger when `ApplyBufferedLedgersWork.cpp` throws an error here: https://github.com/stellar/stellar-core/blob/59cce0d057de88eef9c06a2c0c121f352e592ce3/src/catchup/ApplyBufferedLedgersWork.cpp#L51-L57


Here is an example of what it might look like:

![image](https://user-images.githubusercontent.com/7690119/131580531-6bd6a718-8d60-4dd5-ad68-932af227214d.png)


The issue is that, currently, `ApplyBufferedLedgersWork` expects that `mSyncingLedgers` has information for the red section. One idea that @marta-lokhova and I discussed is to update `ApplyBufferedLedgersWork` such that it downloads history for the red section.

While we download the red part, `mSyncingLedgers` will continue to move. Some potential solutions to this are:
- Download more history to cover parts of `mSyncingLedgers` so it's okay if it moves a little.
- After completing the download, check if more history needs to be downloaded.

It seems to me that some combination of the two approaches would probably solve the issue. However, it seems that a careful analysis with some back-of-the-envelope calculation may be necessary to find how much history should be downloaded, how many ledgers can be stored in `mSyncingLedgers` without affecting memory usage too much, ...

**Comment by MonsieurNicolas** [comment]
That sounds overly complicated:
I think a better strategy is to just let the current "catchup" work complete (potentially on a ledger much earlier than whatever the network is doing) and let core re-trigger catchup.

Then, the goal is to keep just enough ledgers in the buffered set such that we can trigger catchup based off historical data.
We already have some logic (see `trimAndReset`) to discard buffered ledgers that we don't need; we just need to expand this to when "catchup" is running but not done.

So you can focus on what the "last" catchup needs (in terms of buffered ledgers) so that it can properly replay ledgers between the just completed catchup run and the tracking ledger.
