### ISSUE TITLE
Audit asynchronous events during application shutdown

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3163]
Discovered in https://github.com/stellar/stellar-core/issues/3106. Application shutdown and IO service shutdown are not synchronous, so it is possible that events get executed in between. The problem is that at this point multiple application components (such as ProcessManager, BucketManager etc) are shutdown. We should audit the code, and ensure that either timers are properly cancelled, or the events triggered no-op if the application is shutting down.

**Comment by MonsieurNicolas** [comment]
As part of this, we should also probably understand if we're shutting down components in the right order and actually doing what we need to do: I suspect that as we've re-organized code, certain things potentially broke.

For example, I don't quite understand why we're doing this busy loop on "Work" that can execute an arbitrary amount of work before shutting down subsystems (which can potentially hang for a very long time on shutdown).

The original intent behind "gracefulStop` was to spend some time (bounded) cleaning up things that we want to cleanup, in particular to avoid leaving temp files on disk; with the "real" shutdown being something a lot dumber (ie: just call all destructors and exit) so that tools like leak checkers can tell us if we missed something.
I think that over time, destructors became more powerful and slow (and can potentially throw etc).
