### ISSUE TITLE
Rogue 0.0000001 -> 1 transactions via pools

### ISSUE THREAD

**Issue by hot-bit-git** [stellar/stellar-core#3301]
Rogue transactions are happening since pools were introduced, causing price charts going wild with some candles going either to 1 or almost 0. Shortly we will have only vertical lines stretching from 0 to 1 instead of the price charts.
![0000001](https://user-images.githubusercontent.com/35734693/147921278-e8c5703d-4de2-4cac-80f2-f31c43465981.png)

This is a MAJOR issue. It could be mitigated to some extent by filtering outliers before rendering the chart, but the problem should be solved at its core and such prices never registered on the ledger.

![1](https://user-images.githubusercontent.com/35734693/147921635-20a6c10a-4219-41b3-a029-f0a8e1f7f190.png)

**Comment by jonjove** [comment]
Hi @hot-bit-git, thank you for the report. I want to emphasize that there is no exploit here. This is a consequence of rounding when performing very small trades. We have accounted for this in the design, so people performing very small trades always get worse prices than are available in the market. Another way of saying this is that stellar-core always rounds in favor of the liquidity pool rather than the trader.

For example, imagine that you wanted to buy 1 stroop of A by selling B. Suppose that the pool contains 3000e7 stroops of A and 1000e7 stroops of B, which means selling ~0.334 stroops of B should be sufficient. But it is impossible to sell a fraction of a stroop, so the protocol sells 1 stroop of B instead. Now, you bought 1 stroop of A for 1 stroop of B. But at market price you could have bought ~3 stroops of A for 1 stroop of B, so this was a bad trade.

The situation described above makes use of `PathPaymentStrictReceive` operation. The relevant computations done by the protocol are described in https://github.com/stellar/stellar-protocol/blob/master/core/cap-0038.md#pathpaymentstrictsendop-and-pathpaymentstrictreceiveop. Specifically, in this case the formula is
```
x = ceil[Xy / (Y - y) / (1 - F)]
```
where
- `x` is the amount sent to the liquidity pool (this is an amount of B in the above example)
- `y` is the amount received from the liquidity pool (eg. 1 stroop of A in the above example)
- `X` is the reserves corresponding to the asset sent to the liquidity pool (eg. 1000e7 stroops of B in the above example)
- `Y` is the reserves corresponding to the asset received from the liquidity pool (eg. 3000e7 stroops of A in the above example)
- `F` is the fee rate (eg. 0.003 in protocol 18)
---------

Having established that this is not an exploit, downstream systems should still handle this case elegantly. Here is an approach that _could_ make sense. Instead of using the trade price to construct a chart, one could use the mid-price (the ratio of the reserves) from the pool after each trade. This would slightly change the meaning of the chart, but would still make a lot of sense. The 1:1 trades didn’t actually move the price of the pool to 1:1—in fact, the price barely changed at all because the quantities involved were very small. So using the pool mid-price, this problem wouldn’t occur. For an analogy that doesn’t involve liquidity pools, consider a traditional order book with offers to sell 10 X for $100 each and sell 10 X for $210 each. If you bought 11 X at market price, the total trade price would be $110 per X but the market actually moved all the way to $210 per X. Displaying the trade price is like what is currently happening, whereas displaying the price the market moved to is like what I’m proposing.

I'm not sure where you encountered that chart, but I would recommend that you open an issue on the appropriate repository.

**Comment by FredericRezeau** [comment]
It may not be an exploit, but we could question the rationale behind having a trade matching engine executing transactions at price levels that no one is asking for both in order books and liquidity pools. The core matching engine logic disrespecting current market bids/asks seems to be the root issue which echoes downstream. Would it not be more logical to have such transactions not be executed and fail on the basis that selling fraction of a stroop is not allowed, rather than applying such arbitrary stroop rounding?

**Comment by jonjove** [comment]
@FredericRezeau I want to emphasize that people are indeed asking for these prices. If you submit `PathPaymentStrictReceive` with `sendMax = 1` and `destAmount = 1`, then you are indeed saying that you will accept a price of 1:1. If the counterparty is a liquidity pool, then it is happy because the constant product invariant is enforced (that's how the conversion formulae are derived). If the counterparty is an order, then it is happy because the trade price must exceed the limit price (that's how the conversion formulae are derived). So everyone is getting what they want.

This behavior developed over the course of several proposals: CAP-0004, CAP-0024, and CAP-0038. At every stage, we considered various alternatives. But ultimately we chose this behavior because everyone is getting what they want. It would be weird for the protocol to not make a trade that everyone is willing to accept--indeed CAP-0004 is all about making it so that never happens. The responsibility is on transaction submitters: if you don't want to get a bad price, submit operations that don't accept bad prices by choosing appropriate `sendMax` and `destMin`.

**Comment by FredericRezeau** [comment]
@jonjove Thanks for your answer. To clarify, I was referring to **price levels**. Because the behavior introduced by the rounding logic disrespects support and resistance through order books and liquidity pools regardless. Downstream systems are only reflecting the behavior creating these _oddities_. Maybe a rejection rule could take precedence provided the stroop is the minimum unit in the system and provide a neutral behavior by leaving the system intact.
