### ISSUE TITLE
loadgen: support a few Soroban transactions

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3706]
We need to perform various load tests analysis for Soroban traffic.

If we want to reuse our existing load testing infra, we need to update `loadgen` to support a few minimalists contracts:
* simple payment, SAC and generic
* AMM swap equivalent

We should also use those as part of our smoke tests

**Comment by mbsdf** [comment]
We only have one transaction that is supported by loadgen

**Comment by MonsieurNicolas** [comment]
I was also chatting with @jayz22 a few days ago that is looking into some sort of "performance benchmarks" (special contracts that we can use to evaluate performance on different hardware types). Maybe we can reuse his work in this context?

**Comment by dmkozh** [comment]
Here are some of my thoughts on the loadgen design:

- Contract design: I think we can come up with a single reasonably simple contract (probably with just 1-2 functions) that would cover most of the relevant resources:
   - take a vector of bytes objects->cover various transaction sizes
   - write every bytes entry to the ledger->cover write counts/write sizes
   - reusing the keys will also exercise the ledger reads, though we could add something to read entries without writing them
   - call some host function(s) in a loop, for a number of times specified as an input argument->cover instructions 
   - maybe emit some events based on the inputs. Not sure it's valuable though, as the events limits are there for the sake of downstream consumers and in core we emit a lot of metadata already.
   - if we want to exercise VM instantiation, we could do sub-contract calls as well, but I'm not sure that's necessary. Also to cover non-cached VMs, we'd need to come up with several Wasms, which is quite of a maintenance burden
   - the same goes for the SAC - we could call it, but I'm not sure it's necessary, at least for the first round of testing. It's not significantly different from any other host function call (the only significant difference being the additional LE type coverage)
 - Resource consumption: if the contract is simple enough, we should be able to roughly estimate the necessary amount of instructions based on the inputs. If that doesn't work, we'll need to do a core version of preflight, which is a lot more work.
   -  We also might want to have some transactions that fail at apply time due to the lack of resources. E.g. fit as many transactions as possible per ledger, but have them all consume a lot of resources actually (to make sure the budget cutoffs work as expected without significant overhead compared to transactions that declare enough resources). Probably not critical, but nice to have
 - Parameter tuning: given the customizable contract, we should be able to configure load generation to produce different types of soroban traffic mixes with the ability to use different distributions for different resources.
- Traffic mix: just supporting the soroban transactions is not enough for the good coverage. We should mix soroban traffic with an appropriate fraction of the classic traffic generation (probably just doing the max possible classic traffic should be good enough)
