### ISSUE TITLE
RO-bump implementation breaks concurrency model

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#3862]
The current implementation of an RO-bump happens, like an RW-bump, on a tx-by-tx basis. When a single tx completes, if it's successful we write the update to the ltx. This induces sequential semantics among all txs that share access to an RO entry, not just RW entries, which will defeat future parallel partitioning. The point of RO entries is to allow parallel reads across partitions.

The correct semantics here entail buffering all committed RO-bumps in a txset, taking a max bump per key, and emitting expiration extension entries just for those. Which I think, unfortunately, will require some level of extension of the commit/rollback logic in the ltx structure.

In some way this bug is therefore similar to #3772 but it is more serious (though I think that one is also serious).

**Comment by MonsieurNicolas** [comment]
As we don't support emitting meta that corresponds to "execution lanes" yet (or even have a design on it), it's probably ok for now? The way we feed changes to the bucket list at the end will not change, it's just the intermediate representation/state that will, right? Or is this tracking something else? Which CAP describes the expected behavior?
