### ISSUE TITLE
Diagnostics affect instruction and memory when they shouldn't

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3902]
Here are the instruction and memory counts for the `Stellar asset contract XLM transfer` test -

Without diagnostics
```
create - ins=138962  mem=8015
invoke - ins=352583  mem=24189
```

With diagnostics
```
create - ins=138977  mem=8095
invoke - ins=352598  mem=24269
```

**Comment by jayz22** [comment]
The diff looks consistent: 
cpu: 15, mem: 80
Can you debug-print the budget when running the tests and see where the difference is?

**Comment by jayz22** [comment]
I think it is due to this line:
https://github.com/stellar/rs-soroban-env/blob/eb5a9ba053a7b64a8eff605db625525378f7bea0/soroban-env-host/src/e2e_invoke.rs#L322C12-L322C12

The `metered_collect` relies on the size hint for budget charging, which is the size of the array pre-filtering.
So its charging depends on the size of the buffer including the diagnostic event.

I'll take this issue.
