### ISSUE TITLE
incorrect iterator reset during eviction scan

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3913]
During scans for eviction, we reset the iterator if the underlying bucket have changed. However, here it looks like we reset the iterator too early, before the new bucket actually spills: https://github.com/stellar/stellar-core/blob/23f3cfb821d79f3958b615e0404d6f6ff446cdaa/src/bucket/BucketList.cpp#L866

This is because ledgerSeq passed to ledgerShouldSpill isn't technically fully closed yet, so the BucketList isn't updated with spills. This means that we reset the iterator, and scan the same bucket again, then scan the new bucket at a wrong offset (therefore, not evicting some entries). 

One way to fix and simplify this logic is to stop relying on ledger sequence spill calculation completely. Instead, we could have a map of active bucket hashes that we're iterating over, and update it as soon as a new ledger is closed, and reset the iterator then.

**Comment by SirTyson** [comment]
I agree that this is a bug, but I think we still must use spill calculations. If I understand your suggestion correctly with the map, we reset the iterator when the hash changes immediately after ledger close. This isn't possible, since we wouldn't be able to write the new iterator position to the BucketList, since the ledger has closed. Assuming the map is in-memory, this means any node joining the network on a spill boundary would have the outdated iterator (since the new iterator wasn't updated) and populate its in-memory map with the new hash. This means the new node would have no way of knowing it should reset it's iterator and would crash.

We need all iterator information to be available to a node joining the network, so I don't think we can use any in-memory structs. We also can't immediately update the EvictionIterator on new Bucket adoption, as the ledger has already closed at that point. I think the only way forward given these constraints is the ledger based spill logic. I agree it's complicated, but I've identified the issue in the unit tests causing us to miss this off by one error, so I think fixing the test and the off by one may be our best bet.

**Comment by marta-lokhova** [comment]
yeah, makes sense; I didn't realize the iterator needs BucketList state that hasn't been produced yet.
