### ISSUE TITLE
Customize random number generator seed on startup

### ISSUE THREAD

**Issue by mbsdf** [stellar/stellar-core#3917]
For test and simulation release, we can have a more deterministic approach. This could be a config parameter. For production version, on node startup, we can start the random number generation, seeding for example with something nondeterministic, for example with time. This is to customize random number generator seed on startup, and to follow up randomness of peer selection.

**Comment by mbsdf** [comment]
It would be good to get @graydon's opinion here

**Comment by MonsieurNicolas** [comment]
When running tests, we already override the global behavior by using a less dynamic seed or allow to set a specific seed -- see https://github.com/stellar/stellar-core/blob/dbcd1d5f55b938b786f5b3fba3434885a19d81da/src/test/test.cpp#L328

We already seed randomness on startup for the most part: see https://github.com/stellar/stellar-core/blob/dbcd1d5f55b938b786f5b3fba3434885a19d81da/src/main/main.cpp#L263 )

The bug is that we forgot to seed `gRandomEngine`. Maybe by making it possible to call https://github.com/stellar/stellar-core/blob/dbcd1d5f55b938b786f5b3fba3434885a19d81da/src/util/Math.h#L64
