### ISSUE TITLE
Allow `ENABLE_SOROBAN_DIAGNOSTIC_EVENTS` with `NODE_IS_VALIDATOR`

### ISSUE THREAD

**Issue by orbitlens** [stellar/stellar-core#4234]
Our ingestion pipeline relies on `ENABLE_SOROBAN_DIAGNOSTIC_EVENTS` option to get extended transactions metadata for Soroban nested contract calls tracking and in-depth storage analysis. 

Docs mention that 
> ENABLE_SOROBAN_DIAGNOSTIC_EVENTS cannot be enabled on validators.

Naturally, on our validator nodes we see the following message:

> 2024-02-20T15:56:44.886 GA23K [default FATAL] Got an exception: ENABLE_SOROBAN_DIAGNOSTIC_EVENTS is set, NODE_IS_VALIDATOR is set, and RUN_STANDALONE is not set

We switched to the non-validating mode, but after that all our nodes started to lag behind the consensus by 2-4 ledgers. That's not acceptable for our case, because our explorer doesn't show real-time ledger state in this case.

Could you please allow enabling `ENABLE_SOROBAN_DIAGNOSTIC_EVENTS` option on validators? We run Core nodes on dedicated servers with plenty of RAM and fast NVME disks, so we can handle the load.

**Comment by anupsdf** [comment]
Hello @orbitlens, 
Is it possible for you to have a watcher node (non-validator) with ENABLE_SOROBAN_DIAGNOSTIC_EVENTS option to ingest the extended transaction metadata?

**Comment by graydon** [comment]
I'm not sure I understand; a node that is non-validating should not in any way lag consensus. Non-validating just means you don't vote (and in this case it's protective -- to ensure no other validator who _depends on your vote_ gets lagged because you get lagged by diagnostic events). It won't speed your node up.

**Comment by orbitlens** [comment]
@graydon @anupsdf thank you for the suggestions. 

We experimented with the quorum slices and it managed to fix the problem. Removing our own nodes (which are not validators anymore) and adding only conservative set of T1 validators to the quorum did the trick. Plus, we increased `TARGET_PEER_CONNECTIONS` to 16. At the moment we don't experience time lag behind T1 validators consensus anymore.

So my apologies for the false alarm.

Re: diagnostic events DoS. As I understand, you've conducted some test on this internally, right? Are there any particular numbers of Soroban transactions included in the ledger or any other more specific thresholds in terms of possible performance degradation? We run our nodes with `ENABLE_SOROBAN_DIAGNOSTIC_EVENTS` option enabled on dedicated servers with 8 VCPUs, 64 GB RAM and NVME disks. At what point I need to start worrying about the potential DoS and upgrade the hardware?

**Comment by graydon** [comment]
@orbitlens Glad to hear if there's not a bug here!

In terms of the DoS risk, it's not so much that we _expect_ diagnostic events to cause DoS under normal operations, just an abundance of caution since it's user-controlled code. The main risk is that there's a user-facing log facility to inject user-generated data into diagnostic events -- logging from a contract -- and if they choose to users can generate a lot of data maliciously that way. 

To help mitigate this risk there's also a "shadow budget" that limits work related to diagnostic events, and when the shadow budget is exceeded subsequent logging in the transaction -- or anything charged to the shadow budget -- will silently fail. The shadow budget state -- whether it exists, what its balance is, how it gets depleted -- is invisible to the final transaction state / canonical hash of side effects of the transaction. That's why it's called "shadow". So in _theory_ the DoS risk is limited to users causing transactions that both max out their normal budget _and_ do additional logging work that maxes out the shadow budget, which might take something-like-twice-as-long to run as they're budgeted for. Which is potentially enough to disrupt the network if it happens on a bunch of validators -- which is why we ban it there -- but not likely enough to knock a watcher or RPC node out of service, just lag it a bit (ledger close is usually only 0.5-1s out of every 5s ledger period).

(There is also, for emergency operator-diagnosis, the option of an operator running core with log-level set to TRACE, at which point the shadow budget jumps up to I think 500x normal budget, because in that mode soroban writes fairly extensive host-state-summary-data to the trace log on every host function call while the contract runs, and we charge all that extra work to the shadow budget; but that's not visible or controllable by users at all. You might enjoy watching it on console though, and who knows, maybe you really want to ingest high-resolution execution traces?)
