### ISSUE TITLE
Block credits with XLM currency code

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/stellar-core#448]
In order to prevent potential confusion, and to maintain the sanctity of XLM, stellar-core should reject transactions that attempt to send credit with the currency code XLM.

**Comment by MonsieurNicolas** [comment]
on that front, do we want to make currency codes case insensitive and low
ASCII only? Right now I don't think we enforce anything.
This includes things like use of "space" or other special characters in
there.

**Comment by irisli** [comment]
+1 on having a clear defined currency code case (as to not repeat https://github.com/stellar/stellard/issues/90 )

I think this is a must have before the live network is launched so that we don't have to do backwards support for ledger cruft.

Drawing from inspiration: http://counterparty.io/docs/counterparty_features/#creating-assets
Counterparty limits it to: `A unique string of 4 to 12 uppercase Latin characters (inclusive) not beginning with ‘A’. `

I think whatever we do, we just need a very clear definition

**Comment by MonsieurNicolas** [comment]
We have a different currency type for custom length asset strings.
For ISO like, I'd say we can go with something simple that will minimize chances of collisions:
mandatory 3 characters (A-Z only), with an optional 1 character prefix (A-Za-z).
so that people can do things like mUSD as we don't have exponents for those type of currencies.

**Comment by thejollyrogers** [comment]
"do things like mUSD"
That doesn't make sense. Issue a credit that's a fraction of another
credit, but specified in the name of the currency?
That is really weird and doesn't work in the system. For example this would
mean that I could set a trustline to issuer A for
mBTC but someone with a trustline to issuer A for BTC wouldn't be able to
hold my mBTC credits. There would need to be an
exchange for each fractional type.

**Comment by MonsieurNicolas** [comment]
You would most likely not have people trade many of these. I used mUSD but that was misleading - it would be for some currency ABC where the exchange rate is so high that we drive balances out of bound (ie, can't represent 1,000,000 BTC in this other currency).

Alternative is to use one as the bytes as a signed exponent (base 10) to apply to the stored balance if this makes it clearer.

Note that this is a client side thing: core doesn't care about multipliers and where the fixed point precision is (math is performed on opaque 64 bit "amounts"), but we still want to have some standardization on how amounts are used in clients to avoid complexity.

**Comment by jedmccaleb** [comment]
I can see making it case insensitive although I don't really see the issue with allowing whatever. You are trusting the gateway in the first place so them "tricking" you into holding some weird currency code is the least of your worries.

The issue iris pointed to doesn't really pertain to the new code.

**Comment by MonsieurNicolas** [comment]
as it seems we're going with human codes (both for input and reading), case sensitivity is an anti-usability pattern that can only lead to problems (not malicious, just failed transactions in general).

Alternative is to just punt everything client side and use actual currency numbers:
reserve 0-999 for ISO 4217 http://en.wikipedia.org/wiki/ISO_4217#Currency_numbers and leave everything else to just be whatever people want.
This may make it more obvious to people: issuer is the namespace and number is something traded in that namespace. A user has to go to the issuer's web site to get a description of what they are dealing with.

**Comment by jedmccaleb** [comment]
just imagining some currencies where you might want case sensitivity: mBTC  24k  OxO O.o 
idk it feels like it is better to just allow people to do what they want here. It is really a client
side issue.
Adding the currencies you trust will be done by clicking on a link.  so not much room for user error there.
Selecting what currency you want to send will be done via a drop down so again not much room for error there.

**Comment by MonsieurNicolas** [comment]
So are we saying that ISO is not ISO then if we allow anything?
I would have imagined that the arbitrary strings were going to be covered
with the non ISO case - the difference client side being that ISO is very
restricted in terms of values, are usable by humans and need very little
handling client side as they are pretty uniform across organizations
(following what ISO says), so that "USD" means "US Dollar".

The non ISO format allows for people to trade anything named after emojis
or other locale specific things but like you said, will require clients to
make all experiences clickable in some way and not rely on user input.

**Comment by thejollyrogers** [comment]
My gut feeling says allowing someone to issue credits that say "XLM" will lead to phishing attacks.

**Comment by jedmccaleb** [comment]
I don't see why we would limit it to just ISO. (That means no BTC btw) The client just has to display the 4 letter string if it is strict ISO or not.

We could block "XLM". I agree that could be confusing.

**Comment by MonsieurNicolas** [comment]
Yeah at some point Bhutan may decide to move to BTC just for fun.

I am fine with taking an "opaque" approach to this field (as in, it's just a string), but I'd like to hear which magic we're going to do on the client side in order to promote best practices so that people never have to input those things manually and have a way to understand/lookup what issuers are and what they are trading from this issuer.
Then the only other open issue I see after this is deciding if we want to have the exponent as part of this or not: clients should be able to display amounts properly, my recommendation was to use the first byte as a signed exponent that indicates how to convert the amount. So most of the time we would have "-7" there (0xF9), so that we have 11.7 digits in the UI (and not expose people too much to rounding errors).

I don't think we should block XLM and friends:
* there are too many to block "xlm", "x1m", "xlm.", "STR", etc
* an XLM issuer can provide additional services/guarantees that cannot be done using native XLM (insured payment, reversal for example)
* it's just a special case where we need to teach people about the trust model of currency/issuers pairs. I don't see why XLM scams should be harder than BTC scams.

**Comment by thejollyrogers** [comment]
Adding an "exponent" byte to the currency code opens the door for buggy client software and headaches on the part of integrators. We should stick with fixed point with 6 significant digits for all currencies, sorry bitcoin no satoshis can be sent (you can't even send a satoshi in normal bitcoin, there is a 5.46uBTC minimum output size that was added in 0.8.2). But that also gives an upper bound of about 10 trillion, which I also think is acceptable. IMO, good software is opinionated and I think these contraints are reasonable for 99% of use cases of sending currency. If we start delineating amounts by a byte in the currency code we're opening up a can of worms.
