### ISSUE TITLE
understand why we need code in CreatePassiveOfferOpFrame::CreatePassiveOfferOpFrame

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#529]
The duplication in the way the mCreateOp member is setup seems to indicate some sort of underlying issue. Potentially a memory corruption (according to Jed, without it things didn't work).

https://github.com/stellar/stellar-core/blob/master/src/transactions/CreatePassiveOfferOpFrame.cpp#L14-L20

The following block is not needed as mCreateOp is setup by CreatePassiveOfferOpFrame::createMangeOfferOp

```C++
        mCreateOp.body.type(MANAGE_OFFER);
        mCreateOp.body.manageOfferOp().amount = op.body.createPassiveOfferOp().amount;
        mCreateOp.body.manageOfferOp().takerGets = op.body.createPassiveOfferOp().takerGets;
        mCreateOp.body.manageOfferOp().takerPays = op.body.createPassiveOfferOp().takerPays;
        mCreateOp.body.manageOfferOp().offerID = 0;
        mCreateOp.body.manageOfferOp().price = op.body.createPassiveOfferOp().price;
        mCreateOp.sourceAccount = op.sourceAccount;
```

**Comment by graydon** [comment]
This is actually a UMR, if it works for you it's just by accident. You're referencing `mCreateOp` before it's initialized, in a call to the base class ctor, before the derived class initializers run.

This is fixable a few ways; the idiomatically easiest is by moving `mCreateOp` to a separate class and inheriting that class _before_ `ManageOfferOpFrame` so that the member is initialized before you get into calling the `ManageOfferOpFrame` ctor. I have a fix and confirm that this removes the UMR.
