### ISSUE TITLE
compilation ko on ubuntu 14.04

### ISSUE THREAD

**Issue by FredericHeem** [stellar/stellar-core#621]
Compilation fails on an ubuntu 14.04:
```
make -C ./src/lib/xdrpp
make[1]: Entering directory `/home/frederic/stellar-core/src/lib/xdrpp'
/bin/bash ./ylwrap xdrc/scan.ll .c xdrc/scan.cc -- /bin/bash /home/frederic/stellar-core/src/lib/xdrpp/missing flex  
updating lex.yyxdrc/scan.cc
mv: cannot move ‘tmp-scan.cc’ to ‘../lex.yyxdrc/scan.cc’: No such file or directory
```

Any ideas ?

**Comment by graydon** [comment]
It sounds like maybe you're missing flex. I'm not sure it will build out of git without flex, might only work from tarballs (i.e. with the generated sources pregenerated).

**Comment by FredericHeem** [comment]
That's weird because flex is installed ...

**Comment by graydon** [comment]
I'm not sure otherwise; it builds for me on 14.04. Which rev are you building? Can you paste a complete config.log somewhere?

**Comment by FredericHeem** [comment]
It seems to be a autogen/configure cache issue, flex has been installed after first running them. It now compiles fine with a fresh clone.
Would the stellar team consider using CMake instead of the horrendous autoconf/automake/configure crap ?

**Comment by graydon** [comment]
Glad it's working for you now. Let us know if you have further difficulties.

Re: CMake, We discussed it at some length, along with a few other options (stellard is in scons), back when starting the rewrite and settled on autotools due to its widespread standardization and support. I think at this point we're uninterested in revisiting build system decisions.
