### ISSUE TITLE
Should we make it where different networks are unable to connect to each other?

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#692]
For example we have the testnet and there will be a live network. We don't want these nodes to connect to each other accidentally. People should be clear in their configs which they want to talk to.

Also maybe people will set up their own networks and ideally these wouldn't accidentally connect to each other either.

We can use the `overlayVersion` in the HELLO message or we can add another byte there or do we need to do something more fundamental? Maybe even the account keys should have a different leading byte?

**Comment by nullstyle** [comment]
It's also worth discussing adding a field to a TransactionEnvelope that ensures a transaction bound for one network cannot be applied to another network.  Certainly, one recommendation we could have would be "don't reuse secrets across networks" but that doesn't really help people who accidentally do so.

**Comment by jedmccaleb** [comment]
After talking with graydon and scott we are leaning toward just making these networks incompatible at the overlay level. This means that testnet nodes won't even be able to connect to livenet nodes. Addresses will still be the same between both. This seems low risk though since you have to make accounts explicitly so accounts shouldn't actually exist in both networks. And seq numbers certainly won't be the same between both even if the accounts do exist on both.

**Comment by MonsieurNicolas** [comment]
I would say that the only concern I would have with just using overlay as the way to make the networks incompatible is that it makes it possible to use messages signed with one network for another. Best to me would be to just break up the use of EnvelopeType https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-ledger-entries.x#L203 to be something like [network ID _ 24 bits] | [envelope type _ 8 bits ]
Then the problem shifts to be "have a consensus for not reusing network IDs globally". Which should is relatively simple with 24 bits of address space (real networks actually used by people would pick IDs not overlapping from the start, test networks we don't care - we could make it a convention that "0-31" are the IDs of test networks for example).

**Comment by stanford-scs** [comment]
I feel strongly A) that different networks should not be able to interoperate, and B) that whatever it is that identifies a network is strongly tied to the owner of the initial coins.  For example, we could name a network by the public key in the genesis block, or by the collision-resistant hash of the genesis block.

**Comment by jedmccaleb** [comment]
@stanford-scs  why does it matter how the network is identified?

**Comment by stanford-scs** [comment]
Because ultimately the reason you care about the identity of the network is that it tells you the value of the coins.  The test net is separate from the production net because a test net coin is not the same as a real coin.

**Comment by irisli** [comment]
I think that testnet and mainnet should also have different looking addresses too kinda like how Bitcoin has addresses starting with 9 and c. This way, the distinction between testnet and mainnet will be clear and explicit that keys should be used in one network. Thats kinda the main point of having a version number in base encoded addresses. It'll also be useful for when we have multiple testnets and they can each have their own version prefix. Though I'm not sure that this will solve the non-incompatibility issue since this is just cosmetic and users can just use the same seed. Perhaps this paragraph is to go into a different but related issue. 

As for the internal operation of how they will be i compatible, I just think that transactions signed in one shouldn't be portable to another. How it is implemented is not really something I can comment about.

**Comment by stanford-scs** [comment]
That's an interesting idea, but I disagree.  We want the testnet to be using all the same codepaths as the real network, so definitely don't want an altered encoding.  That suggests we would have to tag addresses generically with the name of the particular network they belong to.  But in order to name networks in an egalitarian way, we would need at least 20 bytes.

That said, if you care strongly about this, one compromise would be to have both absolute and relative addresses.  So an absolute address is super long, like (tag,pubkey)@(genesis-block-hash).  Almost everywhere in the UI, the @(genesis-block-hash) part would be implicit (either testnet or production).  However, for people writing software or scripts that want to be explicit about addresses, they could specify it explicitly to avoid something weird happening in the wrong context.

**Comment by MonsieurNicolas** [comment]
We decided on combining the concepts of genesis passphrase and network hashing, this way we clearly isolate instances.

**Comment by buhrmi** [comment]
A bit late on the issue, but I don't like the idea of isolating the networks. Features like quorum and validator sets should be able to address this issue, no? Just remove the testnet nodes from the quorom, add the live nodes, and it's good to go, no?

**Comment by MonsieurNicolas** [comment]
Isolating network is a way to solve avoiding double spending between networks, without it we would have to have a different scheme in place (and not as secure).
Without it, you can imagine somebody taking the transaction history of a test network (for example), watch the public network and inject the right signed transactions from the test network at the right time for profit.

**Comment by buhrmi** [comment]
But the chances that there is a profitable address exploitable via replay attack between networks should be neglectable small given the address space. Unless somebody uses the same address for testnet and livenet in which case the fault lies not with the network.

**Comment by MonsieurNicolas** [comment]
Yeah this is to avoid exactly that, we can't expect most people to know about different networks. It's a "secure by default" type of situation.

**Comment by buhrmi** [comment]
... for varying definitions of "secure".
