### ISSUE TITLE
need endpoint of webrpc for querying account

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#722]
if we have a endpoint query sequence number of account,  simple client can talk directly to stellar-node bypassing horizon/sqldb.

Request:
/q?acct=<G******>
Response:
{
"account": "G***",
"seqn": "1"
}

**Comment by sacarlson** [comment]
yes I think I understand what your saying.  otherwise at present you can't do any transactions without access to the stellar.db to access the next_sequence for an account.  Is that what your saying?
I don't think it would require very many lines of codes to add that feature.   But with that lookup you might as well add to the return account balance in each asset and maybe trustlines.  But what is the cost of this in performance, development time and other?  Who would make use of it?  At this point I think I would have used it.

**Comment by MonsieurNicolas** [comment]
I don't think stellar-core is the right place to do this: we intentionally stayed away from any code that deals with clients as there are much better stacks to write web facing services.
You can achieve what you are trying to do by just writing a micro-horizon type of service (in node or whatever), that way you can imagine adding support for various encodings, eventing, etc in the future (I don't know what you are trying to do with just read access to ledger entries, or are you writing something like client side validation of transactions?).
That said the better approach might be to refactor Horizon so that it's more modular?
