### ISSUE TITLE
Assertion failed: (fs::exists(lock)), function getBucketDir, file bucket/BucketManagerImpl.cpp, line 130.

### ISSUE THREAD

**Issue by FredericHeem** [stellar/stellar-core#773]
After upgrading to the latest code from a fresh new clone, *stellar-core* stopped working due to the following assert:
```
Assertion failed: (fs::exists(lock)), function getBucketDir, file bucket/BucketManagerImpl.cpp, line 130.
```

Shouldn't the code properly handle this case even in production build ?

**Comment by FredericHeem** [comment]
Creating the *buckets* directory make the assert go away.

**Comment by MonsieurNicolas** [comment]
Was that after you did --newdb ?

**Comment by FredericHeem** [comment]
The assert was hit before reseting the db. Let's try to remove the *buckets* directory to find out the outcome. 
Why not adding an if and exit the process in case it eventually happens again in production mode where assert are removed from the code ?

**Comment by MonsieurNicolas** [comment]
We do not have a build flavor with NDEBUG, but I get your point.

We left asserts in the code for situations that should not happen and would indicate bugs, but I see this one may be more common and deserves to be first class if it's part of normal operation.

The database and buckets folder work in lockstep: one should not exist without the other (newdb creates both).
Do you have additional information on how you got to this state? Did you remove the folder manually?

**Comment by FredericHeem** [comment]
To get to this state, stellar-core was running solo from a 2 weeks old version with postgres, after updating to the latest version, it didn't compile even after a *make clean* (time to switch to CMake ?). So stellar-core was compiled from a fresh clone. At that point, the assert was hit. The workaround is to manually create the  *buckets* directory.

**Comment by MonsieurNicolas** [comment]
I see - it probably didn't compile because you need to run configure and make, not just make.
As far as why you run into this particular problem, I imagine that after you build from fresh, the working folder that it used was different from the one it was using before (but was still pointing to the same database).
I am modifying the code to throw an exception for this case ;
note that in general we don't have any sanity check that the buckets folder and the database are in sync, so if two binaries share the db state but not the buckets folder state (like stale folder, empty folder), you will may run into all sorts of hard to debug scenarios that will cause the node to fail at getting in sync (bad hash).
