### ISSUE TITLE
not recognizing self in validator list

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#831]
This fails now:
```
NODE_SEED="seed for one of the below validators"
FAILURE_SAFETY=0
UNSAFE_QUORUM=true

[QUORUM_SET]
THRESHOLD_PERCENT=51
VALIDATORS=["GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y", "GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP", "GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z"]
```
Why does isQuorumSetSaneInternal need to do more than check for the existence of NODE_SEED public key?

**Comment by MonsieurNicolas** [comment]
I can't repro this issue and will need the actual config that you're using.

The only other test in there is the threshold one: if a threshold can never be met, then yeah it's invalid and things will never work which is why it should fail (but you're probably not running into this - 51% is within range)
