### ISSUE TITLE
show last SCP msg emitted in /info

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#908]

**Comment by MonsieurNicolas** [comment]
why? it seems we can just ask people to call /scp (that includes this information)

**Comment by jedmccaleb** [comment]
/scp isn't usable except to use for debugging.  It would be nice to see where you are in the SCP process at a glance

**Comment by MonsieurNicolas** [comment]
I added a limit to the scp endpoint since then to get this type of information; the "last SCP message" seems like debugging information to me. I don't think there is a short version that makes sense to be included in "info" - if there is, I would be glad to add it. Right now we only say "joining SCP" and don't bother with trying to explain why for example.
